In [1727]:
import pandas as pd
import gdown
import os
import numpy as np

In [1728]:
dict_plikow = {
    'towar': 'https://drive.google.com/file/d/1BnYuwCY4A7fzb5Vg36r6vpCbRhM_acDZ/view?usp=drive_link',
    'pozdok': 'https://drive.google.com/file/d/1q9x3lCAb9u0BPqbEzGJLhdkESDon33Sl/view?usp=drive_link',
    'dok':'https://drive.google.com/file/d/1ONZ1yvmTAsGq1P9FieuZvyRINUNHj1dk/view?usp=drive_link',
    'asort': 'https://drive.google.com/file/d/15vZYClznfSQDGO_qS0gPJ3J9Vo5ZKzsS/view?usp=sharing'
}

In [1729]:
force_redownload = False  # ustaw True, gdy chcesz odświeżyć dane
file_path = "dane"

for key, url in dict_plikow.items():
    file_path = f"dane/{key}.parquet"
    if os.path.exists(file_path) and not force_redownload:
        print(f"Plik {file_path} już istnieje - pomijam.")
        continue
    gdown.download(url, file_path, quiet=False)

Plik dane/towar.parquet już istnieje - pomijam.
Plik dane/pozdok.parquet już istnieje - pomijam.
Plik dane/dok.parquet już istnieje - pomijam.
Plik dane/asort.parquet już istnieje - pomijam.

#  DOK

In [1730]:
pozdok = pd.read_parquet('dane/pozdok.parquet', engine='pyarrow')

In [1731]:
pozdok.columns

Index(['DokId', 'Kolejnosc', 'NrPozycji', 'TowId', 'TypPoz', 'IloscPlus',
       'IloscMinus', 'PoziomCen', 'Metoda', 'CenaDomyslna', 'CenaPrzedRab',
       'RabatProc', 'CenaPoRab', 'Wartosc', 'CenaDet', 'CenaMag', 'Stawka',
       'TypTowaru', 'IleWZgrzewce', 'StawkaDod', 'Netto', 'Podatek',
       'SledzPartii', 'UUID'],
      dtype='str')

In [1732]:
pozdok = pozdok.drop(columns=['IleWZgrzewce','StawkaDod','Netto','Podatek','SledzPartii', 'UUID','Metoda','PoziomCen']).copy()

In [1733]:
pozdok.columns

Index(['DokId', 'Kolejnosc', 'NrPozycji', 'TowId', 'TypPoz', 'IloscPlus',
       'IloscMinus', 'CenaDomyslna', 'CenaPrzedRab', 'RabatProc', 'CenaPoRab',
       'Wartosc', 'CenaDet', 'CenaMag', 'Stawka', 'TypTowaru'],
      dtype='str')

In [1734]:

asort = pd.read_parquet('dane/asort.parquet')

In [1735]:
asort=asort.drop(columns=['OpcjaMarzy',
'HurtRabat',
'OpcjaRabatu',
'NocNarzut',
'OpcjaNarzutu',
'CentrAsId',
'UkrytyNaPanelach',
'UkrytyNaBonowniku',
'BezAutoEtykiet',
'Param1',
'Autoryzacja'
]).copy()

In [1736]:
asort.sample(10)

     AsId                                    Nazwa  Marza
322   215                  RYBY WĘDZONE WAGA /ryby   0.25
132   261                     Admat warzywa i mixy   0.00
94    181  KWIATY, DONICZKI I DODATKI /przemysłowe   0.00
314   202               OWOCOWE /przetwory owocowe   0.25
276   224                            GUMY DO ŻUCIA   0.00
72    156     PŁATKI ŚNIADANIOWE /zbożowe i sypkie   0.00
271   219                                  CIASTKA   0.00
284   353                  Wcielone z Transportera   0.00
102   189                   TEKSTYLIA /przemysłowe   0.00
27     39              KETCHUPY /dodatki spożywcze   0.00

## Towar

In [1737]:
towar = pd.read_parquet('dane/towar.parquet')

In [1738]:
towar=towar.drop(columns=['JMId',
'KatId',
'Producent',
'ArtId',
'Skrot',
'TypTowaru',
'Indeks1',
'Indeks2',
'Opis1',
'Opis2',
'Opis3',
'Opis4',
'TermWazn',
'HurtRabat',
'NocNarzut',
'OpcjaMarzy',
'OpcjaRabatu',
'OpcjaNarzutu',
'CenaNoc',
'CenaDod',
'CenaOtwarta',
'PoziomCen',
'PrefPLU',
'IleWZgrzewce',
'IleWCalosci',
'Opis4',
'TermWazn',
'HurtRabat',
'NocNarzut',
'OpcjaMarzy',
'OpcjaRabatu',
'OpcjaNarzutu',
'CenaNoc',
'CenaDod',
'CenaOtwarta',
'PoziomCen',
'PrefPLU',
'IleWZgrzewce',
'IleWCalosci',
'KodZgrzewki',
'Aktywny',
       'Waga', 'Szerokosc', 'Wysokosc', 'Glebokosc', 'CKU', 'BlokDostawcow',
       'BlokCenyZak', 'BlokCenSp', 'BlokZmian', 'Rezerwa1', 'Rezerwa2',
       'CentrTowId', 'Zmiana', 'Akcyzowy', 'SledzPartii', 'MaxCenaZak',
       'PrzeliczJM', 'NrDrukarki', 'Cena5', 'Cena6', 'ProgPromocji',
       'ZmianaIstotna', 'ZmianaTylkoCen', 'Przeznaczenie', 'ObslugaPartii',
       'UkrycNaKasie', 'KodCN', 'MinCenaSp', 'SubsysKoduGlownego', 'StatusZam',
       'KodGlownyCentralny', 'NowoscOd', 'NowoscPrzez',
       'WysylacNaSklepInternetowy', 'GrupaGTU', 'KrajIdPochodzenia', 'Zywnosc',
       'KodSklepu','CenaHurt','CenaEw','Stawka'
]).copy()

In [1739]:

dok = pd.read_parquet('dane/dok.parquet')

In [1740]:
dok = dok.drop(columns=['UzId',
'MagId',

'DataDod',
'DataPom',

'Opcja1',
'Opcja2',
'Opcja3',
'Opcja4',
'CenyZakBrutto',
'Opcja3',
'Opcja4',
'CenyZakBrutto',

'Opcja1',
'Opcja2',
'Opcja3',
'Opcja4',
'CenyZakBrutto',
'Kwota1', 'Kwota2', 'Kwota3', 'Kwota4',
       'Kwota5', 'Kwota6', 'Kwota7', 'Kwota8', 'Kwota9', 'Kwota10', 'Param1',
       'Param2', 'Param3', 'Param4', 'EksportFK', 'Zmiana',
       'NrKolejnyMag', 'Param5', 'Param6', 'Kwota11', 'Kwota12', 'WalId',
       'Kurs', 'CentrDokId', 'Opcja5', 'Opcja6', 'Opcja7', 'Opcja8',
       'ZmianaPkt', 'ZaplaconoPodatek', 'ZaplaconoWKasie', 'WalIdPlatnosci',
       'DataWystKSeF', 'DaneWystId', 'Opcja9', 'Opcja10', 'Opcja11', 'Opcja12',
       'Kwota13', 'Kwota14', 'Kwota15', 'Kwota16', 'UUID','CenySpBrutto','FormaPlat','TerminPlat','NettoUslugi','PodatekUslugi','PodatekUslugi',
       'PodatekDetUslugi', 'NettoMag', 'PodatekMag',
       'NettoMagUslugi', 'PodatekMagUslugi', 'Razem', 'DoZaplaty',
       'Zaplacono','PoziomCen','NettoDet','PodatekDet','NettoDetUslugi'

]).copy()

In [1741]:
dok['Data'] = pd.to_datetime(dok['Data'], errors='coerce').copy()

## Usuwam te rekordy które w NrDok maja "NaN"

In [1742]:
dok = dok[dok['NrDok'].notna()]

#  POZDOK

In [1743]:
pozdok = pozdok.drop_duplicates()

## Łacze dok oraz pozdok

In [1744]:
pozdok_dok = pd.merge(pozdok, dok, on="DokId", how="left")

In [1745]:
pozdok_dok

,DokId,Kolejnosc,NrPozycji,TowId,TypPoz,IloscPlus,IloscMinus,CenaDomyslna,CenaPrzedRab,RabatProc_x,...,TypTowaru,Data,KolejnyWDniu,NrDok,TypDok,Aktywny,RabatProc_y,Netto,Podatek,NrKolejny
0,41775,2,1,19623,0,1.00,0.00,745.65,917.15,0.00,...,0,2018-09-14,519.00,1/09/L,33.00,1.00,0.00,917.15,210.94,NaN
1,131173,1,1,23638,0,1.00,0.00,0.00,112.50,0.00,...,2,2019-01-07,178.00,FV/19/4,33.00,1.00,0.00,112.50,25.88,NaN
2,142162,1,1,23638,0,1.00,0.00,0.00,75.00,0.00,...,2,2019-01-21,1.00,FV/19/7,33.00,1.00,0.00,75.00,17.25,NaN
3,159723,1,1,23638,0,1.00,0.00,0.00,7956.81,0.00,...,2,2019-02-11,305.00,FV/19/9,33.00,1.00,0.00,7956.81,1830.07,NaN
4,162945,1,1,25390,0,1.00,0.00,100.04,100.00,0.00,...,0,2019-02-22,2.00,FV/19/10,33.00,1.00,0.00,100.00,23.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4272651,2237660,14,14,81803,4,1.00,0.00,5.28,5.28,0.00,...,0,2026-01-31,947.00,DF/PAR/260131/12424/2,21.00,1.00,0.04,87.71,8.52,NaN
4272652,2237660,15,15,81638,4,1.00,0.00,0.50,0.50,0.00,...,6,2026-01-31,947.00,DF/PAR/260131/12424/2,21.00,1.00,0.04,87.71,8.52,NaN
4272653,2237660,16,16,52905,4,1.00,0.00,2.43,2.43,0.00,...,0,2026-01-31,947.00,DF/PAR/260131/12424/2,21.00,1.00,0.04,87.71,8.52,NaN
4272654,2237660,17,17,80379,4,1.00,0.00,15.44,15.44,0.00,...,0,2026-01-31,947.00,DF/PAR/260131/12424/2,21.00,1.00,0.04,87.71,8.52,NaN
4272655,2237661,1,1,53755,4,0.20,0.00,44.71,44.71,0.00,...,0,2026-01-31,948.00,DF/PAR/260131/12425/2,21.00,1.00,0.00,9.12,2.10,NaN

In [1746]:
pozdok_dok=pozdok_dok.drop(columns=['RabatProc_y']).copy()

In [1747]:
pozdok_dok=pozdok_dok.rename(columns={'RabatProc_x': 'RabatProc'}).copy()

In [1748]:
asort = asort.rename(columns={'Nazwa': 'Nazwa_asort'})

In [1749]:
towar = towar.rename(columns={'Nazwa': 'Nazwa_towar'})

In [1750]:
towar = towar.drop_duplicates()

In [1751]:
towar['Kod'] = towar['Kod'].fillna(0)
towar['Kod']=towar['Kod'].astype('int')

## Łacze dataframes  "towar" oraz "asort" powstaje "towar_asort"

In [1752]:
towar_asort = pd.merge(towar, asort, on="AsId", how="left")

In [1753]:
towar_asort.sample(3)

,TowId,AsId,Nazwa_towar,Kod,Marza_x,CenaDet,Nazwa_asort,Marza_y
4291,14706,189,RAJSTOPY GABRIELLA DEN20,5906733300248,0.00,4.07,TEKSTYLIA /przemysłowe,0.00
14592,24491,86,PRZECENA JOGURT NATURALNY ACTIVIA 180G DANONE,279,0.20,1.70,JOGURTY /nabiał,0.00
37088,36869,120,CHLEB ŻYTNI Z ŻURAWINĄ 500G MAREL,5901764232056,0.20,6.18,CHLEBY,0.00

## Łacze dataframes  "pozdok_dok" oraz "towar_asort" powstaje "pozdok_dok_towar_asort"

In [1754]:
df = pd.merge(pozdok_dok, towar_asort, on="TowId", how="left")

In [1755]:
df.Data.min(), df.Data.max()

(Timestamp('2006-01-27 00:00:00'), Timestamp('2026-02-02 00:00:00'))

In [1756]:
df = df[df['Data'].between('2023-01-01', '2025-12-31')].copy()

In [1757]:
df = df.dropna(subset=['TypDok'])

In [1758]:
df = df.rename(columns={'TowId': 'SKU'})

In [1759]:
df = df[df['Nazwa_towar'].notna()]

In [1760]:
df = df.drop(columns=['CenaDomyslna','CenaPrzedRab','RabatProc','CenaDet_x','CenaMag','Stawka','TypTowaru','Netto','Podatek','Marza_y']).copy()

In [1761]:
df=df.rename(columns={'CenaDet_y': 'CenaDet', 'Marza_x': 'Marza'}).copy()

In [1762]:
df['CenaDet'] = df['CenaDet'].astype('float')

max_cena = df['CenaDet'].max()

df['TypDok'] = df['TypDok'].astype('int')

In [1763]:
df[df['CenaDet'] == max_cena]

,DokId,Kolejnosc,NrPozycji,SKU,TypPoz,IloscPlus,IloscMinus,CenaPoRab,Wartosc,Data,...,NrDok,TypDok,Aktywny,NrKolejny,AsId,Nazwa_towar,Kod,Marza,CenaDet,Nazwa_asort
193101,1216669,15482,14187,51781,3,0.00,-1.00,0.00,0.00,2023-02-19,...,REM/23/9,16,1.00,NaN,354.00,Zestaw materiałów i urządzeń do osuszania budy...,234.00,0.00,3089.43,xinne
1572660,1601036,16846,14333,51781,3,0.00,0.00,3089.43,0.00,2024-02-25,...,REM/24/16,16,1.00,NaN,354.00,Zestaw materiałów i urządzeń do osuszania budy...,234.00,0.00,3089.43,xinne
2598655,1842411,20620,19151,51781,3,0.00,0.00,3089.43,0.00,2024-11-10,...,REM/24/76,16,1.00,NaN,354.00,Zestaw materiałów i urządzeń do osuszania budy...,234.00,0.00,3089.43,xinne
3198038,1982216,12015,12015,51781,3,-1.00,0.00,0.00,0.00,2023-01-01,...,BO/23/1,14,1.00,NaN,354.00,Zestaw materiałów i urządzeń do osuszania budy...,234.00,0.00,3089.43,xinne
3218150,1982218,11779,11779,51781,3,0.00,0.00,0.00,0.00,2023-01-01,...,BO/23/2,14,1.00,NaN,354.00,Zestaw materiałów i urządzeń do osuszania budy...,234.00,0.00,3089.43,xinne

In [1764]:
df = df[df['Nazwa_towar'] != 'USŁUGA MARKETINGOWA']

## Analiza czasowa

- sprzedaż w czasie (miesięcznie/tygodniowo) — Data
- które miesiące/dni mają największy obrót

In [1765]:
df['Data'] = pd.to_datetime(df['Data'])

# Kolumny czasowe
df['Rok'] = df['Data'].dt.year
df['Miesiac'] = df['Data'].dt.month
df['RokMiesiac'] = df['Data'].dt.to_period('M')
df['DzienTygodnia'] = df['Data'].dt.dayofweek  # 0=pon, 6=nd

In [1766]:
lista_typdok = df['TypDok'].value_counts().index.tolist()

In [1767]:

# for l in lista_typdok:
#     df_temp = df[df['TypDok'] == l]
#     print(f"\n--- TypDok: {l} ---")
#     display(df_temp.sample(1))

In [1768]:
niedziele_handlowe = pd.to_datetime([
    # 2022
    '2022-01-30', '2022-04-10', '2022-04-24', '2022-06-26', '2022-08-28', '2022-12-11', '2022-12-18',
    # 2023
    '2023-01-29', '2023-04-02', '2023-04-30', '2023-06-25', '2023-08-27', '2023-12-10', '2023-12-17',
    # 2024
    '2024-01-28', '2024-03-24', '2024-04-28', '2024-06-30', '2024-08-25', '2024-12-15', '2024-12-22',
    # 2025
    '2025-01-26', '2025-04-13', '2025-04-27', '2025-06-29', '2025-08-31', '2025-12-14', '2025-12-21'
])

In [1769]:
long_weekend_dates = [
    # ===== 2022 =====
    "2022-01-01", "2022-01-02",
    "2022-01-06", "2022-01-07", "2022-01-08", "2022-01-09",
    "2022-04-16", "2022-04-17", "2022-04-18",
    "2022-06-16", "2022-06-17", "2022-06-18", "2022-06-19",
    "2022-10-29", "2022-10-30", "2022-10-31", "2022-11-01",
    "2022-11-11", "2022-11-12", "2022-11-13",
    # ===== 2023 =====
    "2023-04-08", "2023-04-09", "2023-04-10",
    "2023-06-08", "2023-06-09", "2023-06-10", "2023-06-11",
    "2023-08-12", "2023-08-13", "2023-08-14", "2023-08-15",
    "2023-10-28", "2023-10-29", "2023-10-30", "2023-10-31", "2023-11-01",
    # ===== 2024 =====
    "2024-01-01",
    "2024-03-30", "2024-03-31", "2024-04-01",
    "2024-05-30", "2024-05-31", "2024-06-01", "2024-06-02",
    "2024-08-15", "2024-08-16", "2024-08-17", "2024-08-18",
    "2024-11-01", "2024-11-02", "2024-11-03",
    "2024-11-09", "2024-11-10", "2024-11-11",
    # ===== 2025 =====
    "2025-04-19", "2025-04-20", "2025-04-21",
    "2025-06-19", "2025-06-20", "2025-06-21", "2025-06-22",
    "2025-08-15", "2025-08-16", "2025-08-17",
]

In [1770]:

df['Data'] = pd.to_datetime(df['Data'], errors='coerce')

df['IloscPlus']   = pd.to_numeric(df['IloscPlus'],   errors='coerce').fillna(0)
df['IloscMinus']  = pd.to_numeric(df['IloscMinus'],  errors='coerce').fillna(0)
df = df.dropna(subset=['Data'])
df['Data'] = df['Data'].dt.floor('D')
df['czy_remanent'] = df['TypDok'] == 16


df = df.dropna(subset=['NrDok'])
df = df.rename(columns={'TowId_Log': 'SKU'})

# Dokumenty IP_IM_DELTA: ilosc_netto w źródle = 0, liczymy samodzielnie
# (TypDok: 16=REM, 26=ROZB, 78=PRZES, 88=PRZES_GR)
ip_im_mask = df['TypDok'].isin([16, 26, 78, 88])
df.loc[ip_im_mask, 'ilosc_netto'] = (
    df.loc[ip_im_mask, 'IloscPlus'] - df.loc[ip_im_mask, 'IloscMinus']
)
# TypDok 21 (sprzedaż) — towar wychodzi, ilosc_netto ujemna
sprzedaz_mask = df['TypDok'] == 21
df.loc[sprzedaz_mask, 'ilosc_netto'] = -df.loc[sprzedaz_mask, 'IloscMinus']
df['Ruch'] = df['ilosc_netto']

# Dni tygodnia
df['nazwa_dnia'] = df['Data'].dt.dayofweek.map({
    0: 'Poniedziałek', 1: 'Wtorek', 2: 'Środa',
    3: 'Czwartek', 4: 'Piątek', 5: 'Sobota', 6: 'Niedziela'
})

# Flagi specjalnych dni
df['dlugi_weekend']    = df['Data'].isin(long_weekend_dates)
df['niedziela_handlowa'] = df['Data'].isin(niedziele_handlowe)

# Kategoria dnia
def kategoryzuj(row):
    if row['niedziela_handlowa']:
        return 'Niedziela handlowa'
    if row['dlugi_weekend']:
        return 'Długi weekend'
    return row['nazwa_dnia']

df['kategoria_dnia'] = df.apply(kategoryzuj, axis=1)

# Cena detaliczna


# Daty przecen per SKU – bez Nazwa, żeby nie tworzyć Nazwa_x/Nazwa_y przy merge
# daty_przecen = (
#     df[df['TypDok'].isin([18, 19])][['SKU', 'Data']]
#     .drop_duplicates()
# )
# daty_przecen['czy_przecena'] = True
# df = df.merge(daty_przecen, on=['SKU', 'Data'], how='left')
# df['czy_przecena'] = df['czy_przecena'].fillna(False)

# Słownik nazw 
etykiety = (
    df[df['Nazwa_towar'].notna()][['SKU', 'Nazwa_towar']]
    .drop_duplicates('SKU')
    .set_index('SKU')
)
wszystkie_ids = pd.DataFrame({'SKU': df['SKU'].unique()})
wszystkie_ids = wszystkie_ids.merge(etykiety.reset_index(), on='SKU', how='left')
wszystkie_ids['Nazwa_towar'] = wszystkie_ids['Nazwa_towar'].fillna(
    wszystkie_ids['SKU'].astype(str).apply(lambda x: f'[ID {x}]')
)
wszystkie_ids = wszystkie_ids.sort_values('Nazwa_towar').reset_index(drop=True)

# Uzupełnij Nazwa w df
df['Nazwa_towar'] = df['SKU'].map(wszystkie_ids.set_index('SKU')['Nazwa_towar'])
df['Nazwa_towar'] = df['Nazwa_towar'].fillna(df['SKU'].astype(str).apply(lambda x: f'[ID {x}]'))

print(f"Wierszy: {len(df):,}  |  SKU: {df['SKU'].nunique():,}  |  Zakres: {df['Data'].min().date()} – {df['Data'].max().date()}")
df.sample(3)

Wierszy: 4,137,985  |  SKU: 21,865  |  Zakres: 2023-01-01 – 2025-12-31

,DokId,Kolejnosc,NrPozycji,SKU,TypPoz,IloscPlus,IloscMinus,CenaPoRab,Wartosc,Data,...,Miesiac,RokMiesiac,DzienTygodnia,czy_remanent,ilosc_netto,Ruch,nazwa_dnia,dlugi_weekend,niedziela_handlowa,kategoria_dnia
3144180,1972934,3,3,66965,4,1.00,0.00,8.12,8.12,2025-04-02,...,4,2025-04,2,False,-0.00,-0.00,Środa,False,False,Środa
1613799,1609813,1,1,77932,4,1.00,0.00,12.99,12.99,2024-03-06,...,3,2024-03,2,False,-0.00,-0.00,Środa,False,False,Środa
1189761,1450482,3,3,4240,4,1.00,0.00,7.99,7.99,2023-11-18,...,11,2023-11,5,False,-0.00,-0.00,Sobota,False,False,Sobota

# Stan magazynowy

#### Tylko cukier

In [1771]:
df_cukier = df[df['SKU'] == 11398].copy()

In [1772]:
df_sugar = pd.read_csv('cukier.csv', sep=';', encoding='utf-8-sig')
df_sugar.IloscMinus = df_sugar.IloscMinus.fillna(0)
df_sugar.IloscPlus = df_sugar.IloscPlus.fillna(0)
df_sugar['Data'] = pd.to_datetime(df_sugar['Data'])



# ============================================================
# 2. ILOSC_NETTO - wpływ każdej operacji na stan magazynowy
#    (+) zwiększa stan, (-) zmniejsza, 0 = brak wpływu
# ============================================================
def oblicz_ilosc_netto(df):
    df = df.copy()
    ip, im, td, akt = df['IloscPlus'], df['IloscMinus'], df['TypDok'], df['Aktywny']

    netto = ip - im                                    # domyślnie (TypDok 26, 88, aktywny remanent 16)
    netto = np.where(td.isin([21]), -ip, netto)    # sprzedaż (PAR/FA) - zmniejsza stan
    netto = np.where(td == 10, -ip, netto)             # RW - rozchód wewnętrzny - zmniejsza stan
    netto = np.where(td == 2,  ip, netto)              # PZ - przyjęcie zewnętrzne - zwiększa stan
    netto = np.where(td == 14, ip, netto)              # BO - bilans otwarcia - stan początkowy
    netto = np.where(td == 23, ip, netto)              # ST - storno (zwrot) - zwiększa stan
    # netto = np.where(td.isin([18, 19, 50]), 0, netto)  # przeceny - brak wpływu na stan

    # Remanent NIEAKTYWNY (draft, zastąpiony innym wpisem tego samego dnia) -> brak wpływu
    netto = np.where((td == 16) & (akt == 0), 0, netto)

    df['ilosc_netto'] = netto
    return df


# ============================================================
# 3. STAN MAGAZYNOWY narastająco per SKU
#    - sortowanie wg KolejnyWDniu (rzeczywista kolejność w ciągu dnia),
#      Kolejnosc jako tiebreaker dla pozycji z tego samego dokumentu
#    - aktywny remanent (TypDok=16, Aktywny=1) RESETUJE stan do wyniku spisu (IloscPlus)
# ============================================================
def oblicz_stany(df):
    df = df.sort_values(['SKU', 'Data', 'KolejnyWDniu', 'Kolejnosc']).reset_index(drop=True)
    wyniki = []
    for sku, grupa in df.groupby('SKU', sort=False):
        grupa = grupa.copy()
        stan = 0.0
        stany, stany_przed = [], []
        for _, row in grupa.iterrows():
            stany_przed.append(stan)
            if row['TypDok'] == 16 and row['Aktywny'] == 1:
                stan = row['IloscPlus']      # reset do wyniku spisu z natury
            else:
                stan += row['ilosc_netto']
            stany.append(stan)
        grupa['Stan_przed'] = stany_przed    # stan tuż PRZED tym wierszem (walidacja remanentu)
        grupa['Stan'] = stany                # stan PO tym wierszu
        wyniki.append(grupa)
    return pd.concat(wyniki, ignore_index=True)


df_c = oblicz_ilosc_netto(df_sugar)
df_c = oblicz_stany(df_c)


# ============================================================
# 4. ZESTAWIENIE: WSZYSTKIE remanenty (aktywne i nieaktywne)
# ============================================================
rem = df_c[df_c['TypDok'] == 16].copy()

zestawienie = rem[['SKU', 'Nazwa_towar', 'Data', 'Aktywny']].copy()
zestawienie['Stan_algorytm_przed'] = rem['Stan_przed']
zestawienie['Stan_wg_Inka (IloscMinus)'] = rem['IloscMinus']
zestawienie['Spis_z_natury (IloscPlus)'] = rem['IloscPlus']
zestawienie['roznica_vs_Inka'] = rem['Stan_przed'] - rem['IloscMinus']
zestawienie['Stan_po'] = rem['Stan']

# Oznacz dni z wieloma remanentami
liczba_w_dniu = rem.groupby(['SKU','Data']).size().rename('liczba_remanentow_w_dniu')
zestawienie = zestawienie.merge(liczba_w_dniu, on=['SKU','Data'])

print("=== WSZYSTKIE remanenty (aktywne + nieaktywne) ===")
display(zestawienie)

=== WSZYSTKIE remanenty (aktywne + nieaktywne) ===

,SKU,Nazwa_towar,Data,Aktywny,Stan_algorytm_przed,Stan_wg_Inka (IloscMinus),Spis_z_natury (IloscPlus),roznica_vs_Inka,Stan_po,liczba_remanentow_w_dniu
0,11398,CUKIER BIAŁY KRÓLEWSKI 1KG SUDZUCKER,2023-02-19,0.00,539.00,294.00,91.00,245.00,539.00,2
1,11398,CUKIER BIAŁY KRÓLEWSKI 1KG SUDZUCKER,2023-02-19,1.00,539.00,294.00,282.00,245.00,282.00,2
2,11398,CUKIER BIAŁY KRÓLEWSKI 1KG SUDZUCKER,2024-02-25,1.00,3436.00,178.00,177.00,3258.00,177.00,1
3,11398,CUKIER BIAŁY KRÓLEWSKI 1KG SUDZUCKER,2024-11-10,1.00,1589.00,137.00,132.00,1452.00,132.00,1

### Stan magazyniowy dla wszystkich produktów

In [1773]:
df = oblicz_ilosc_netto(df)
df = oblicz_stany(df)


# ============================================================
# 4. ZESTAWIENIE: WSZYSTKIE remanenty (aktywne i nieaktywne)
# ============================================================
rem = df[df['TypDok'] == 16].copy()

zestawienie = rem[['SKU', 'Nazwa_towar', 'Data', 'Aktywny']].copy()
zestawienie['Stan_algorytm_przed'] = rem['Stan_przed']
zestawienie['Stan_wg_Inka (IloscMinus)'] = rem['IloscMinus']
zestawienie['Spis_z_natury (IloscPlus)'] = rem['IloscPlus']
zestawienie['roznica_vs_Inka'] = rem['Stan_przed'] - rem['IloscMinus']
zestawienie['Stan_po'] = rem['Stan']

# Oznacz dni z wieloma remanentami
liczba_w_dniu = rem.groupby(['SKU','Data']).size().rename('liczba_remanentow_w_dniu')
zestawienie = zestawienie.merge(liczba_w_dniu, on=['SKU','Data'])

print("=== WSZYSTKIE remanenty (aktywne + nieaktywne) ===")
display(zestawienie)

=== WSZYSTKIE remanenty (aktywne + nieaktywne) ===

,SKU,Nazwa_towar,Data,Aktywny,Stan_algorytm_przed,Stan_wg_Inka (IloscMinus),Spis_z_natury (IloscPlus),roznica_vs_Inka,Stan_po,liczba_remanentow_w_dniu
0,5,TEQUILA OLMECA GOLD 38% 700ML WYBOROWA,2023-02-19,1.00,0.00,0.00,0.00,0.00,0.00,1
1,5,TEQUILA OLMECA GOLD 38% 700ML WYBOROWA,2024-02-25,1.00,0.00,0.00,0.00,0.00,0.00,1
2,5,TEQUILA OLMECA GOLD 38% 700ML WYBOROWA,2024-11-10,1.00,0.00,0.00,0.00,0.00,0.00,1
3,15,SOS TABASCO RED 57ML DEVELEY,2023-02-19,1.00,1.00,1.00,0.00,0.00,0.00,1
4,15,SOS TABASCO RED 57ML DEVELEY,2024-02-25,1.00,9.00,2.00,2.00,7.00,2.00,1
...,...,...,...,...,...,...,...,...,...,...
54272,80828,"HERB PRYNCYTORCIK CLASSIC 28,5G DR GERARD",2025-11-21,1.00,-43.00,-42.00,198.00,-1.00,198.00,1
54273,80913,BATON DARE CARAMEL 20G ETI,2025-11-21,1.00,-2.00,-2.00,0.00,0.00,0.00,1
54274,80999,BATON PAWEŁEK GRUSZKA 45G WEDEL,2025-11-21,1.00,36.00,-1.00,0.00,37.00,0.00,1
54275,81231,LIZAK CHUPA CHUPS STRANGER SZT VAN MELLE,2025-11-21,1.00,3.00,3.00,0.00,0.00,0.00,1
54276,81324,FILET ŚLEDŹ.BATATY 280G LISNER,2025-12-10,1.00,7.00,1.00,0.00,6.00,0.00,1

![opis](dane/2.png)

![opis](dane/1.png)

# OBRÓT miesięczny

In [1774]:
pd.options.display.float_format = '{:.2f}'.format
sprzedaz_mies = df.groupby('RokMiesiac')['Wartosc'].sum().reset_index()
sprzedaz_mies.columns = ['Okres', 'Wartosc']
print(sprzedaz_mies)

      Okres    Wartosc
0   2023-01 1394396.37
1   2023-02 1041717.21
2   2023-03 1291334.66
3   2023-04 1205180.04
4   2023-05 1229945.82
5   2023-06 1200958.24
6   2023-07 1157653.18
7   2023-08 1267128.47
8   2023-09 1251569.65
9   2023-10 1352625.43
10  2023-11 1309340.77
11  2023-12 1323591.76
12  2024-01 1321457.90
13  2024-02 1205869.38
14  2024-03 1431320.12
15  2024-04 1362896.41
16  2024-05 1231791.81
17  2024-06 1225369.19
18  2024-07 1326122.29
19  2024-08 1275344.92
20  2024-09 1256358.58
21  2024-10 1421977.19
22  2024-11 1269184.73
23  2024-12 1420760.65
24  2025-01 1374902.82
25  2025-02 1258449.33
26  2025-03 1313298.76
27  2025-04 1360729.77
28  2025-05 1238554.53
29  2025-06 1203547.73
30  2025-07 1206723.84
31  2025-08 1160489.15
32  2025-09 1237574.68
33  2025-10 1269523.22
34  2025-11 1120889.20
35  2025-12 1306844.72

# Analiza sprzedazy

In [1775]:
sprzedaz_21 = df[df['TypDok'] == 21].copy()
sprzedaz_21['rok']    = sprzedaz_21['Data'].dt.year
sprzedaz_21['miesiac'] = sprzedaz_21['Data'].dt.month
sprzedaz_21['dzien']   = sprzedaz_21['Data'].dt.day
sprzedaz_21['okres']  = sprzedaz_21['Data'].dt.to_period('M').astype(str)

In [1776]:
print(sprzedaz_21['ilosc_netto'].describe())
print(sprzedaz_21['ilosc_netto'].value_counts().head(20))

count   3386607.00
mean         -1.08
std           0.78
min        -100.00
25%          -1.00
50%          -1.00
75%          -1.00
max          -0.00
Name: ilosc_netto, dtype: float64
ilosc_netto
-1.00     2971992
-2.00       70008
-3.00       35948
-4.00       30330
-0.50       15352
-6.00       10222
-5.00        9459
-10.00       2930
-8.00        2025
-0.20        1670
-0.20        1624
-0.00        1586
-0.21        1570
-0.20        1562
-0.20        1561
-0.21        1553
-0.21        1527
-0.21        1314
-0.20        1308
-0.15        1303
Name: count, dtype: int64

####  Top 10 najlepiej sprzedających się produktów w miesiącu

In [1777]:
ranking_miesieczny = (
    sprzedaz_21
    .assign(ilosc_netto=sprzedaz_21['ilosc_netto'].abs())
    .groupby(['kategoria_dnia', 'rok', 'miesiac', 'Nazwa_towar', 'SKU'])['ilosc_netto']
    .sum()
    .reset_index()
    .sort_values(['kategoria_dnia', 'rok', 'miesiac', 'ilosc_netto'],
                  ascending=[True, True, True, False])
)

top10 = ranking_miesieczny.groupby(['kategoria_dnia', 'rok', 'miesiac']).head(10)
top10

,kategoria_dnia,rok,miesiac,Nazwa_towar,SKU,ilosc_netto
194,Czwartek,2023,1,BUŁKA KAJZERKA 50G MAREL,96,361.00
3124,Czwartek,2023,1,TORBA RECYKLING SPAR 30X55 1SZT,38960,226.00
201,Czwartek,2023,1,Bulka poznanska 0.1,86,120.00
2259,Czwartek,2023,1,PIECZYWO MIX,75,117.00
203,Czwartek,2023,1,"Butelka zwrotna 0,5",18674,90.00
...,...,...,...,...,...,...
801007,Środa,2025,12,BUŁKA ZIARNO MIX,92,78.00
803536,Środa,2025,12,PĄCZEK SZT,99,78.00
801968,Środa,2025,12,"KAWA ROZP SASZ JACOBS 3W1 15,2G",18746,75.00
801010,Środa,2025,12,"Butelka zwrotna 0,5",18674,73.00
804291,Środa,2025,12,"WODA MIN N/GAZ MUSZYNIANKA 1,5L MUSZYNIANKA",10022,64.00

In [1778]:
ranking_miesieczny

,kategoria_dnia,rok,miesiac,Nazwa_towar,SKU,ilosc_netto
194,Czwartek,2023,1,BUŁKA KAJZERKA 50G MAREL,96,361.00
3124,Czwartek,2023,1,TORBA RECYKLING SPAR 30X55 1SZT,38960,226.00
201,Czwartek,2023,1,Bulka poznanska 0.1,86,120.00
2259,Czwartek,2023,1,PIECZYWO MIX,75,117.00
203,Czwartek,2023,1,"Butelka zwrotna 0,5",18674,90.00
...,...,...,...,...,...,...
801282,Środa,2025,12,CUKIERKI JELLY KG ROSHEN,67321,0.34
801784,Środa,2025,12,JAJECZKA KG MIESZKO,53755,0.30
801301,Środa,2025,12,CUKIERKI MIX KG ABK,78440,0.24
801271,Środa,2025,12,CUKIERKI BIM BOM KG ROSHEN,78598,0.14
800939,Środa,2025,12,BRZUSZKI Z ŁOSOSIA WĘDZONE KG,25652,0.13

## które SKU generują 80% obrotu

In [1779]:
# Sprzedaż per SKU (tylko TypDok 21 i 59)
sprzedaz_sku = (
    df[df['TypDok'].isin([21])]
    .groupby(['SKU', 'Nazwa_towar'])
    .agg(
        wolumen=('IloscPlus', 'sum'),
        wartosc=('Wartosc', 'sum')
    )
    .reset_index()
    .sort_values('wartosc', ascending=False)
)

# Udział skumulowany
sprzedaz_sku['udzial_proc'] = (
    sprzedaz_sku['wartosc'] / sprzedaz_sku['wartosc'].sum() * 100
)
sprzedaz_sku['udzial_kum'] = sprzedaz_sku['udzial_proc'].cumsum()

# Segment Pareto
sprzedaz_sku['pareto'] = sprzedaz_sku['udzial_kum'].apply(
    lambda x: 'A (top 80%)' if x <= 80 
    else 'B (80-95%)' if x <= 95 
    else 'C (ogon)'
)

print(sprzedaz_sku['pareto'].value_counts())
print()
print(f"Łączna wartość sprzedaży: {sprzedaz_sku['wartosc'].sum():,.0f}")
display(sprzedaz_sku.head(20))

pareto
C (ogon)       6995
B (80-95%)     3177
A (top 80%)    2827
Name: count, dtype: int64

Łączna wartość sprzedaży: 17,885,160

,SKU,Nazwa_towar,wolumen,wartosc,udzial_proc,udzial_kum,pareto
4480,49624,BANAN /KG,18376.67,110389.56,0.62,0.62,A (top 80%)
17,75,PIECZYWO MIX,29969.00,100234.80,0.56,1.18,A (top 80%)
821,4685,WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC,4022.00,92349.42,0.52,1.69,A (top 80%)
2171,11978,WÓDKA ŻOŁĄDKOWA DE LUX 40% 500ML STOCK,3466.00,79877.51,0.45,2.14,A (top 80%)
2609,15149,PAPIEROSY WINSTON BLUE SUPER LINE JTI,4954.00,72051.92,0.40,2.54,A (top 80%)
2951,17470,SER PROMOCJA KG,2636.32,66562.93,0.37,2.92,A (top 80%)
34,96,BUŁKA KAJZERKA 50G MAREL,77712.00,62163.39,0.35,3.26,A (top 80%)
2608,15148,PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI,4050.00,59032.64,0.33,3.59,A (top 80%)
2313,13117,PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS,4235.00,58871.16,0.33,3.92,A (top 80%)
7287,55191,MASŁO EKSTR A 83% 200G SPAR,8478.00,56892.55,0.32,4.24,A (top 80%)
3362,23551,BILET 4.40,13356.00,54413.26,0.30,4.54,A (top 80%)
5561,52261,PAPIEROSY L&M FIRST CUT SSL 20SZ PM,3940.00,54079.23,0.30,4.85,A (top 80%)
2772,16491,SER ZŁOTY MAZUR MLEKPOL KG,1830.21,52330.40,0.29,5.14,A (top 80%)
1464,7741,MIKS KOST MLEMIX ZAMBROWSKI 200G MLEKPOL,8630.00,51969.54,0.29,5.43,A (top 80%)
27,86,Bulka poznanska 0.1,34910.00,50563.99,0.28,5.71,A (top 80%)
11,68,Chleb mieszany krojony 0.6kg PRECELEK,10401.00,49478.21,0.28,5.99,A (top 80%)
383,2383,OLEJ KUJAWSKI 1L KRUSZWICA,5070.00,46209.46,0.26,6.25,A (top 80%)
2185,12108,"WÓDKA ŻUBR STRONG 37,5% 90ML STOCK",6999.00,45380.75,0.25,6.50,A (top 80%)
8345,66340,PAPIEROSY L&M FIRST CUT ZIELONE SSL PM,3273.00,44632.09,0.25,6.75,A (top 80%)
2605,15145,PAPIEROSY WINSTON BLUE 100S 20SZT JTI,3133.00,44179.15,0.25,7.00,A (top 80%)

### Ile % SKU to segment A:

In [1780]:
total_sku = len(sprzedaz_sku)
sku_A = (sprzedaz_sku['pareto'] == 'A (top 80%)').sum()
print(f"Segment A: {sku_A} SKU = {sku_A/total_sku*100:.1f}% wszystkich SKU generuje 80% obrotu")
print(f"Segment C: {6977} SKU = {6977/total_sku*100:.1f}% wszystkich SKU generuje tylko 5% obrotu")

Segment A: 2827 SKU = 21.7% wszystkich SKU generuje 80% obrotu
Segment C: 6977 SKU = 53.7% wszystkich SKU generuje tylko 5% obrotu

In [1781]:
# Dodaj segment Pareto do głównego df
df = df.merge(
    sprzedaz_sku[['SKU', 'pareto']], 
    on='SKU', 
    how='left'
)
df['pareto'] = df['pareto'].fillna('D (brak sprzedaży)')
print(df['pareto'].value_counts())

pareto
A (top 80%)           3060916
B (80-95%)             743211
C (ogon)               277927
D (brak sprzedaży)      55931
Name: count, dtype: int64

### Które produkty sprzedają się najlepiej

In [1782]:
# Top 20 produktów po wartości sprzedaży
print("=== TOP 20 po wartości ===")
display(
    sprzedaz_sku[['Nazwa_towar', 'wartosc', 'wolumen', 'udzial_proc']].sort_values('wartosc', ascending=False)
    .head(20)
)

=== TOP 20 po wartości ===

,Nazwa_towar,wartosc,wolumen,udzial_proc
4480,BANAN /KG,110389.56,18376.67,0.62
17,PIECZYWO MIX,100234.80,29969.00,0.56
821,WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC,92349.42,4022.00,0.52
2171,WÓDKA ŻOŁĄDKOWA DE LUX 40% 500ML STOCK,79877.51,3466.00,0.45
2609,PAPIEROSY WINSTON BLUE SUPER LINE JTI,72051.92,4954.00,0.40
2951,SER PROMOCJA KG,66562.93,2636.32,0.37
34,BUŁKA KAJZERKA 50G MAREL,62163.39,77712.00,0.35
2608,PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI,59032.64,4050.00,0.33
2313,PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS,58871.16,4235.00,0.33
7287,MASŁO EKSTR A 83% 200G SPAR,56892.55,8478.00,0.32
3362,BILET 4.40,54413.26,13356.00,0.30
5561,PAPIEROSY L&M FIRST CUT SSL 20SZ PM,54079.23,3940.00,0.30
2772,SER ZŁOTY MAZUR MLEKPOL KG,52330.40,1830.21,0.29
1464,MIKS KOST MLEMIX ZAMBROWSKI 200G MLEKPOL,51969.54,8630.00,0.29
27,Bulka poznanska 0.1,50563.99,34910.00,0.28
11,Chleb mieszany krojony 0.6kg PRECELEK,49478.21,10401.00,0.28
383,OLEJ KUJAWSKI 1L KRUSZWICA,46209.46,5070.00,0.26
2185,"WÓDKA ŻUBR STRONG 37,5% 90ML STOCK",45380.75,6999.00,0.25
8345,PAPIEROSY L&M FIRST CUT ZIELONE SSL PM,44632.09,3273.00,0.25
2605,PAPIEROSY WINSTON BLUE 100S 20SZT JTI,44179.15,3133.00,0.25

In [1783]:
# Top 20 po wolumenie (ilości sztuk)
print("=== TOP 20 po wolumenie (sztuki) ===")
display(
    sprzedaz_sku[['Nazwa_towar', 'wolumen', 'wartosc']]
    .sort_values('wartosc', ascending=False)
    .head(20)
)

=== TOP 20 po wolumenie (sztuki) ===

                                       Nazwa_towar  wolumen   wartosc
4480                                     BANAN /KG 18376.67 110389.56
17                                    PIECZYWO MIX 29969.00 100234.80
821            WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC  4022.00  92349.42
2171        WÓDKA ŻOŁĄDKOWA DE LUX 40% 500ML STOCK  3466.00  79877.51
2609         PAPIEROSY WINSTON BLUE SUPER LINE JTI  4954.00  72051.92
2951                               SER PROMOCJA KG  2636.32  66562.93
34                        BUŁKA KAJZERKA 50G MAREL 77712.00  62163.39
2608  PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI  4050.00  59032.64
2313    PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS  4235.00  58871.16
7287                   MASŁO EKSTR A 83% 200G SPAR  8478.00  56892.55
3362                                    BILET 4.40 13356.00  54413.26
5561           PAPIEROSY L&M FIRST CUT SSL 20SZ PM  3940.00  54079.23
2772                    SER ZŁOTY MAZUR MLEKPOL KG  1830.21  52330.40
1464      MIKS KOST MLEMIX ZAMBROWSKI 200G MLEKPOL  8630.00  51969.54
27                             Bulka poznanska 0.1 34910.00  50563.99
11        Chleb mieszany krojony 0.6kg    PRECELEK 10401.00  49478.21
383                     OLEJ KUJAWSKI 1L KRUSZWICA  5070.00  46209.46
2185            WÓDKA ŻUBR STRONG 37,5% 90ML STOCK  6999.00  45380.75
8345        PAPIEROSY L&M FIRST CUT ZIELONE SSL PM  3273.00  44632.09
2605         PAPIEROSY WINSTON BLUE 100S 20SZT JTI  3133.00  44179.15

## Na czym się najwięcęj zarabia

In [1784]:
print("=== TOP 20 po marży łącznej ===")
display(
    df[df['TypDok'].isin([21])]
    .groupby('Nazwa_towar')['Marza']
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

=== TOP 20 po marży łącznej ===

Nazwa_towar
TORBA RECYKLING SPAR 30X55 1SZT               8796.80
BANAN /KG                                     5661.20
BUŁKA KAJZERKA 50G MAREL                      4910.00
PIECZYWO MIX                                  4090.40
CYTRYNY TURCJA KG                             3122.28
Bulka poznanska 0.1                           3061.00
Chleb mieszany krojony 0.6kg    PRECELEK      2395.80
Rogal maslany nowy POLPAIN                    2266.00
BUŁKA ZIARNO MIX                              2153.28
ŚMIETANA KUB 18% 200G PIĄTNICA                2120.40
CHLEB MIESZANY KROJONY 500G MAREL             2076.75
SER PROMOCJA KG                               2076.40
JABŁKA POLSKA KG                              1944.80
ZUPA STAND WINIARY BARSZCZ BIAŁY 66G NESTLE   1800.00
MLEKO ŚWIEŻE BUT ŁACIATE 3,2% 1L MLEKPOL      1724.50
MANDARYNKA 1KG LUZ HISZPANIA                  1708.60
CHLEB MIESZANY KROJONY 250G MAREL             1657.00
WODA MIN N/GAZ MUSZYNIANKA 1,5L MUSZYNIANKA   1643.60
SEREK WIEJSKI LEKKI 150G PIĄTNICA             1608.00
CHALKA 0,5KG PRECELEK                         1579.20
Name: Marza, dtype: float64

## Co najlepiej sprzedaje się w piątki

In [1785]:
for i in range(1, 13):
    df_month = df[df['Miesiac'] == i].copy()
    piatki = df_month[(df_month['nazwa_dnia'] == 'Piątek')]
    top = piatki.groupby(['SKU', 'Nazwa_towar']).agg(
    wartosc=('Wartosc', 'sum'),
    ilosc=('ilosc_netto', 'sum')
).sort_values('wartosc', ascending=False)
    print(f"\n=== Miesiąc {i} - TOP Piątki ===")
    display(top.head(5))

=== Miesiąc 1 - TOP Piątki ===

                                                   wartosc   ilosc
SKU   Nazwa_towar
14957 CUKIER KRYSZTAŁ SWEET FAMILY 1KG NORDZUCKER  7222.36 1703.00
49624 BANAN /KG                                    5570.46  251.71
11978 WÓDKA ŻOŁĄDKOWA DE LUX 40% 500ML STOCK       4282.49   95.00
17470 SER PROMOCJA KG                              3982.38   43.29
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC          3797.84   29.00

=== Miesiąc 2 - TOP Piątki ===

                                             wartosc  ilosc
SKU   Nazwa_towar
50008 MANDARYNKA 1KG LUZ HISZPANIA           5362.02 428.47
49624 BANAN /KG                              5243.39 390.54
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC    4149.78  11.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI  4080.29 144.00
17470 SER PROMOCJA KG                        3915.55  81.20

=== Miesiąc 3 - TOP Piątki ===

                                           wartosc  ilosc
SKU   Nazwa_towar
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC  7324.98 183.00
49624 BANAN /KG                            6847.54 635.73
2383  OLEJ KUJAWSKI 1L KRUSZWICA           6030.71 551.00
17470 SER PROMOCJA KG                      5523.96 151.19
12108 WÓDKA ŻUBR STRONG 37,5% 90ML STOCK   5122.10 646.00

=== Miesiąc 4 - TOP Piątki ===

                                              wartosc  ilosc
SKU   Nazwa_towar
49624 BANAN /KG                               4964.15 431.35
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC     4819.03  96.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI   4732.34 184.00
66340 PAPIEROSY L&M FIRST CUT ZIELONE SSL PM  4486.22 274.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM     4135.77 188.00

=== Miesiąc 5 - TOP Piątki ===

                                                    wartosc  ilosc
SKU   Nazwa_towar
49624 BANAN /KG                                     4869.32 330.37
13117 PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS    4862.94 202.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI         4699.81 204.00
15148 PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI  4070.27 193.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM           4028.04 178.00

=== Miesiąc 6 - TOP Piątki ===

                                                  wartosc  ilosc
SKU   Nazwa_towar
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI       5141.49 225.00
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC         4268.08  63.00
13117 PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS  4106.95 182.00
49624 BANAN /KG                                   4023.52 301.50
2383  OLEJ KUJAWSKI 1L KRUSZWICA                  3805.86 318.00

=== Miesiąc 7 - TOP Piątki ===

                                                  wartosc  ilosc
SKU   Nazwa_towar
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI       4597.23 181.00
49624 BANAN /KG                                   4220.93 449.25
13117 PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS  4025.73 154.00
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC         3938.99  52.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM         3490.58 143.00

=== Miesiąc 8 - TOP Piątki ===

                                                    wartosc   ilosc
SKU   Nazwa_towar
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI         5965.77  253.00
23551 BILET 4.40                                    5799.90 1127.00
66340 PAPIEROSY L&M FIRST CUT ZIELONE SSL PM        4549.27  235.00
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC           4424.44   60.00
15148 PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI  4416.18  180.00

=== Miesiąc 9 - TOP Piątki ===

                                             wartosc  ilosc
SKU   Nazwa_towar
51032 WINOGRONO JASNE KG                     4917.56 282.67
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI  4457.07 159.00
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC    4276.43  91.00
23551 BILET 4.40                             4256.63 721.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM    4234.41 170.00

=== Miesiąc 10 - TOP Piątki ===

                                                    wartosc  ilosc
SKU   Nazwa_towar
15148 PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI  5180.87 233.00
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC           4892.96  68.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI         4870.81 178.00
66340 PAPIEROSY L&M FIRST CUT ZIELONE SSL PM        4546.56 212.00
23551 BILET 4.40                                    4244.40 724.00

=== Miesiąc 11 - TOP Piątki ===

                                                    wartosc  ilosc
SKU   Nazwa_towar
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC           5198.88 159.00
49624 BANAN /KG                                     4600.83 354.52
17470 SER PROMOCJA KG                               4514.75 114.23
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI         4022.88 165.00
15148 PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI  4012.99 183.00

=== Miesiąc 12 - TOP Piątki ===

                                           wartosc  ilosc
SKU   Nazwa_towar
49624 BANAN /KG                            5000.98 434.22
4685  WÓDKA ŻUBRÓWKA BIAŁA 40% 500ML CEDC  4251.98  91.00
12108 WÓDKA ŻUBR STRONG 37,5% 90ML STOCK   4023.19 432.00
17470 SER PROMOCJA KG                      3890.81  98.26
55191 MASŁO EKSTR A 83% 200G SPAR          3257.35 212.00

## Co najlepiej sprzedaje się w soboty

In [1786]:
for i in range(1, 13):
    df_month = df[df['Miesiac'] == i].copy()
    sobota = df_month[(df_month['nazwa_dnia'] == 'Sobota')]
    top = sobota.groupby(['SKU', 'Nazwa_towar']).agg(
    wartosc=('Wartosc', 'sum'),
    ilosc=('ilosc_netto', 'sum')
).sort_values('wartosc', ascending=False)
    print(f"\n=== Miesiąc {i} - TOP Soboty ===")
    display(top.head(5))

=== Miesiąc 1 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              4084.25 1366.00
79  CHALKA 0,5KG PRECELEK                     3940.59  377.50
86  Bulka poznanska 0.1                       3869.82 2490.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  3708.55  668.00
139 Rogal maslany nowy POLPAIN                2898.36 1163.00

=== Miesiąc 2 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              6460.12 2245.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  4123.56  845.00
86  Bulka poznanska 0.1                       3963.63 2495.00
79  CHALKA 0,5KG PRECELEK                     3880.86  351.00
139 Rogal maslany nowy POLPAIN                3028.56 1148.00

=== Miesiąc 3 - TOP Soboty ===

                                                wartosc   ilosc
SKU   Nazwa_towar
75    PIECZYWO MIX                              6517.59 2240.00
68    Chleb mieszany krojony 0.6kg    PRECELEK  4519.05  889.00
86    Bulka poznanska 0.1                       4180.16 2527.00
79    CHALKA 0,5KG PRECELEK                     3913.56  327.50
49624 BANAN /KG                                 3480.73 -181.35

=== Miesiąc 4 - TOP Soboty ===

                                               wartosc   ilosc
SKU  Nazwa_towar
68   Chleb mieszany krojony 0.6kg    PRECELEK  5610.96 1087.50
2383 OLEJ KUJAWSKI 1L KRUSZWICA                4780.31  291.00
75   PIECZYWO MIX                              4671.58 1662.00
86   Bulka poznanska 0.1                       4058.83 2647.00
79   CHALKA 0,5KG PRECELEK                     3800.66  360.00

=== Miesiąc 5 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              6139.40 2011.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  3980.42  805.40
79  CHALKA 0,5KG PRECELEK                     3679.34  307.50
86  Bulka poznanska 0.1                       3254.09 1942.00
139 Rogal maslany nowy POLPAIN                2870.23 1074.00

=== Miesiąc 6 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              5262.13 1754.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  3936.39  892.50
86  Bulka poznanska 0.1                       3768.48 2252.00
79  CHALKA 0,5KG PRECELEK                     3727.48  340.00
139 Rogal maslany nowy POLPAIN                2976.06 1104.00

=== Miesiąc 7 - TOP Soboty ===

                                                wartosc   ilosc
SKU   Nazwa_towar
49840 AVOCADO KAL.22/2   1SZT                  34765.94 6640.00
75    PIECZYWO MIX                              4382.72 1470.00
79    CHALKA 0,5KG PRECELEK                     3703.84  328.00
86    Bulka poznanska 0.1                       3384.98 1956.00
68    Chleb mieszany krojony 0.6kg    PRECELEK  3261.15  701.50

=== Miesiąc 8 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              5456.94 1873.00
79  CHALKA 0,5KG PRECELEK                     4494.80  413.00
86  Bulka poznanska 0.1                       3933.14 2254.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  3475.64  769.50
139 Rogal maslany nowy POLPAIN                2992.25 1126.00

=== Miesiąc 9 - TOP Soboty ===

                                                wartosc   ilosc
SKU   Nazwa_towar
75    PIECZYWO MIX                              5679.35 1989.00
86    Bulka poznanska 0.1                       4441.26 2736.00
79    CHALKA 0,5KG PRECELEK                     3961.87  365.00
68    Chleb mieszany krojony 0.6kg    PRECELEK  2934.57  716.50
55191 MASŁO EKSTR A 83% 200G SPAR               2928.70  112.00

=== Miesiąc 10 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              7425.56 2321.00
86  Bulka poznanska 0.1                       4338.90 2625.00
79  CHALKA 0,5KG PRECELEK                     3787.92  351.50
68  Chleb mieszany krojony 0.6kg    PRECELEK  3062.64  705.00
139 Rogal maslany nowy POLPAIN                2900.66 1109.00

=== Miesiąc 11 - TOP Soboty ===

                                              wartosc   ilosc
SKU Nazwa_towar
75  PIECZYWO MIX                              6196.23 1768.00
79  CHALKA 0,5KG PRECELEK                     3969.13  318.00
86  Bulka poznanska 0.1                       3799.74 2225.00
68  Chleb mieszany krojony 0.6kg    PRECELEK  3672.04  771.00
139 Rogal maslany nowy POLPAIN                2988.13 1114.00

=== Miesiąc 12 - TOP Soboty ===

                                                wartosc   ilosc
SKU   Nazwa_towar
75    PIECZYWO MIX                              5068.73 1571.00
86    Bulka poznanska 0.1                       4710.09 3024.00
79    CHALKA 0,5KG PRECELEK                     4651.29  431.00
68    Chleb mieszany krojony 0.6kg    PRECELEK  4644.44  926.50
55191 MASŁO EKSTR A 83% 200G SPAR               3900.51  227.00

In [1724]:
df.sample(5)

,DokId,Kolejnosc,NrPozycji,SKU,TypPoz,IloscPlus,IloscMinus,CenaDomyslna,CenaPrzedRab,RabatProc,...,czy_remanent,ilosc_netto,Ruch,nazwa_dnia,dlugi_weekend,niedziela_handlowa,kategoria_dnia,Stan_przed,Stan,pareto
1785470,1677964,1,1,15445,4,1.00,0.00,9.51,9.51,0.00,...,False,-1.00,-0.00,Piątek,False,False,Piątek,31.00,30.00,A (top 80%)
1937515,1714857,1,1,17398,4,1.00,0.00,3.24,3.24,0.00,...,False,-1.00,-0.00,Wtorek,False,False,Wtorek,135.00,134.00,A (top 80%)
2529751,1983026,3,3,38960,4,1.00,0.00,0.57,0.57,0.00,...,False,-1.00,-0.00,Poniedziałek,False,False,Poniedziałek,1237.00,1236.00,A (top 80%)
64132,2083999,1,1,79,4,0.50,0.00,7.61,7.61,0.00,...,False,-0.50,-0.00,Piątek,False,False,Piątek,51.00,50.50,A (top 80%)
689182,2107064,7,7,5544,4,1.00,0.00,0.82,0.82,0.00,...,False,-1.00,-0.00,Piątek,False,False,Piątek,195.00,194.00,A (top 80%)

In [1789]:
df.niedziela_handlowa.value_counts()

niedziela_handlowa
False    4116164
True       21821
Name: count, dtype: int64

In [1790]:
for i in range(1, 13):
    df_month = df[df['Miesiac'] == i].copy()
    dlugi_weekend = df_month[(df_month['niedziela_handlowa'] == True)]
    top = dlugi_weekend.groupby(['SKU', 'Nazwa_towar']).agg(
    wartosc=('Wartosc', 'sum'),
    ilosc=('ilosc_netto', 'sum')
).sort_values('wartosc', ascending=False)
    print(f"\n=== Miesiąc {i} - TOP Niedziela Handlowa ===")
    display(top.head(5))

=== Miesiąc 1 - TOP Niedziela Handlowa ===

                                                          wartosc  ilosc
SKU   Nazwa_towar
265   CZEKOLADA MLECZNA MILKA 100G MONDELEZ               1485.26 362.00
16866 CZEKOLADA MLECZNA MILKA OREO COOKIES 100G MONDELEZ  1458.90 353.00
17050 CZEKOLADA MLECZNA MILKA HAPPY COWS 100G MONDELEZ    1056.78 252.00
2165  NAPÓJ GAZ COCA-COLA 1,5L COCA-COLA                   982.62 113.00
65714 PTASIE MLECZKO WANILIA 340G WEDEL                    893.86  55.00

=== Miesiąc 2 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 3 - TOP Niedziela Handlowa ===

                                                  wartosc  ilosc
SKU   Nazwa_towar
38543 WÓDKA STUMBRAS PIGWA 0,1L STUMBRAS           371.89  45.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM          287.20  17.00
13117 PAPIEROSY RGD PINK SSL 20SZT PHILIP MORRIS   208.56   4.00
18857 MLEKO ŁOWICKIE 2,0% ŁOWICZ 1L                191.52  48.00
15145 PAPIEROSY WINSTON BLUE 100S 20SZT JTI        187.07   6.00

=== Miesiąc 4 - TOP Niedziela Handlowa ===

                                             wartosc  ilosc
SKU   Nazwa_towar
50771 WÓDKA 1906 38% 0,09L                    561.60  96.00
75    PIECZYWO MIX                            546.50 204.00
38543 WÓDKA STUMBRAS PIGWA 0,1L STUMBRAS      450.70  33.00
15145 PAPIEROSY WINSTON BLUE 100S 20SZT JTI   436.46   6.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI   381.60  10.00

=== Miesiąc 5 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 6 - TOP Niedziela Handlowa ===

                                              wartosc  ilosc
SKU   Nazwa_towar
17985 KAWA ROZP SŁOIK JACOBS VELVET 200G JDE  1121.58  46.00
12290 PIWO PUSZ WARKA  500ML GRUPA ŻYWIEC      813.64 286.00
2383  OLEJ KUJAWSKI 1L KRUSZWICA               647.45  66.00
15149 PAPIEROSY WINSTON BLUE SUPER LINE JTI    563.96  18.00
15145 PAPIEROSY WINSTON BLUE 100S 20SZT JTI    427.52  27.00

=== Miesiąc 7 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 8 - TOP Niedziela Handlowa ===

                                               wartosc  ilosc
SKU   Nazwa_towar
2165  NAPÓJ GAZ COCA-COLA 1,5L COCA-COLA       1085.62 154.00
7722  MASŁO EXTRA KOST ŁACIATE 200G MLEKPOL     709.62 102.00
52261 PAPIEROSY L&M FIRST CUT SSL 20SZ PM       458.54  23.00
23551 BILET 4.40                                457.12  84.00
38354 NAPÓJ GAZ COCA COLA ZERO 1,5L COCA COLA   409.24  63.00

=== Miesiąc 9 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 10 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 11 - TOP Niedziela Handlowa ===

Empty DataFrame
Columns: [wartosc, ilosc]
Index: []

=== Miesiąc 12 - TOP Niedziela Handlowa ===

                                                    wartosc  ilosc
SKU   Nazwa_towar
66340 PAPIEROSY L&M FIRST CUT ZIELONE SSL PM         862.73  54.00
23551 BILET 4.40                                     820.53 191.00
15148 PAPIEROSY WINSTON GREEN SUPER LINE 20SZT JTI   778.64   8.00
66356 PAPIEROSY WINSTON BLACK SSL 20SZT ITI          734.66  27.00
15127 PAPIEROSY CAMEL BLUE SSL 20SZT JTI             681.22  18.00

### Sprawdzam jak się sprzedają kategorie asortyment

In [1791]:
# Agregacja per kategoria
agg = df.groupby(['AsId', 'Nazwa_asort']).agg(
    wartosc=('Wartosc', 'sum'),
    
    ilosc_sku=('SKU', 'nunique'),
    transakcje=('DokId', 'nunique')   
).reset_index()

In [1792]:
agg['wartosc_na_sku'] = (agg['wartosc'] / agg['ilosc_sku']).round(0)

In [1793]:
# Klasyfikacja wg wartość
def klasyfikuj(val):
    if val == 0:   return 'ZERO - brak sprzedaży'
    if val < 0:    return 'UJEMNE - zwroty'
    if val < 500:  return 'MARGINALNE'
    return 'AKTYWNA'

In [1794]:
agg['status'] = agg['wartosc'].apply(klasyfikuj)

In [1795]:
# Podgląd kandydatów do usunięcia
zbedne = agg[agg['status'].isin(['ZERO - brak sprzedaży', 'MARGINALNE'])]
print(f"Kandydaci do usunięcia: {len(zbedne)} kategorii")
display(zbedne[['AsId', 'Nazwa_asort', 'wartosc', 'ilosc_sku', 'status']])

Kandydaci do usunięcia: 57 kategorii

,AsId,Nazwa_asort,wartosc,ilosc_sku,status
31,33.00,DODATKI SPOŻYWCZE,0.00,1,ZERO - brak sprzedaży
44,47.00,x DOŁADOWANIA,0.00,14,ZERO - brak sprzedaży
45,48.00,DOŁADOWANIA I STARTERY,0.00,2,ZERO - brak sprzedaży
48,51.00,PARAFARMACEUTYKI /farmaceutyki,20.93,2,MARGINALNE
50,53.00,ŚRODKI OPATRUNKOWE /farmaceutyki,216.50,15,MARGINALNE
51,54.00,x KOSMETYKI,405.87,30,MARGINALNE
53,56.00,BIO /kosmetyki,0.00,22,ZERO - brak sprzedaży
61,65.00,ZESTAWY I KOSMETYCZKI /kosmetyki,416.83,2,MARGINALNE
101,107.00,OWOCE I WARZYWA,0.00,2,ZERO - brak sprzedaży
120,126.00,"PIZZE, ZAPIEKANKI I CEBULAKI",124.00,4,MARGINALNE
123,131.00,INNE POZOSTAŁE,0.00,2,ZERO - brak sprzedaży
126,135.00,BATONY I WAFELKI DIET /dietetyczne,0.00,11,ZERO - brak sprzedaży
127,136.00,CHLEBY I POCHODNE /dietetyczne,0.00,1,ZERO - brak sprzedaży
128,137.00,INNE DIETETYCZNE /dietetyczne,0.00,7,ZERO - brak sprzedaży
130,139.00,SŁODYCZE DIETETYCZNE /dietetyczne,0.00,2,ZERO - brak sprzedaży
134,145.00,SOKI I NAPOJE,0.00,2,ZERO - brak sprzedaży
159,170.00,AGD I RTV /przemysłowe,0.00,2,ZERO - brak sprzedaży
160,171.00,AKCESORIA DO KĄPIELI /przemysłowe,250.03,12,MARGINALNE
164,176.00,ARTYKUŁY SEZONOWE I DEKORACJE /przemysło,0.00,5,ZERO - brak sprzedaży
166,178.00,"DESKI, SUSZARKI, POKROWCE /przemysłowe",0.00,1,ZERO - brak sprzedaży
168,180.00,INNE /przemysłowe,0.00,3,ZERO - brak sprzedaży
170,183.00,MATERIAŁY PALNE /przemysłowe,0.00,1,ZERO - brak sprzedaży
173,186.00,SERWETKI I OBRUSY /przemysłowe,0.00,17,ZERO - brak sprzedaży
175,188.00,ŚRODKI OWADOBÓJCZE /przemysłowe,264.49,16,MARGINALNE
177,190.00,ZABAWKI /przemysłowe,79.18,11,MARGINALNE
197,210.00,OWOCE MORZA /ryby,0.00,4,ZERO - brak sprzedaży
217,234.00,MARGARYNY DO SMAŻENIA /tłuszcze,0.00,1,ZERO - brak sprzedaży
226,244.00,Domyślny DO WERYFIKACJI + PRZECENY,138.49,2,MARGINALNE
228,247.00,OPAKOWANIA /przemysłowe,491.44,5,MARGINALNE
229,248.00,SMAKOSZ /dodatki spożywcze,0.00,1,ZERO - brak sprzedaży
230,249.00,EKO /nabiał,0.00,1,ZERO - brak sprzedaży
231,252.00,Lubię,0.00,6,ZERO - brak sprzedaży
235,258.00,GROT PIEROGI,0.00,10,ZERO - brak sprzedaży
236,259.00,Grot Surówki i sałatki,0.00,2,ZERO - brak sprzedaży
239,277.00,05 ZAPALNICZKI KIOSK,304.23,17,MARGINALNE
240,278.00,12 PRZEMYSŁOWE KIOSK,1.77,21,MARGINALNE
241,279.00,ŻARÓWKI W KIOSKU,0.00,12,ZERO - brak sprzedaży
242,283.00,06 BILETY W KIOSKU,118.70,5,MARGINALNE
243,284.00,11 LEKI KIOSK,109.33,13,MARGINALNE
244,285.00,01 PAPIEROSY W KIOSKU,0.00,1,ZERO - brak sprzedaży
245,288.00,13 PUNKT DO WERYFIKACJI,0.00,1,ZERO - brak sprzedaży
246,289.00,KARNET I KOPERTY I POCZTÓWKI,75.42,28,MARGINALNE
247,290.00,09 KARTY TEL. doładowania KIOSK,0.00,12,ZERO - brak sprzedaży
248,291.00,TOREBKI,0.00,5,ZERO - brak sprzedaży
249,293.00,02 TYTOŃ W KIOSK,0.00,1,ZERO - brak sprzedaży
252,298.00,ŚWIECE /przemysłowe,392.74,39,MARGINALNE
253,300.00,HERBATY ZIOŁA KAWY /zdrowa,0.00,5,ZERO - brak sprzedaży
265,318.00,LUBIE,0.00,11,ZERO - brak sprzedaży
267,320.00,BIO,0.00,9,ZERO - brak sprzedaży
268,321.00,WEGETARIAŃSKIE/WEGAŃSKIE,93.36,6,MARGINALNE
274,328.00,STRAŻNICY ŚWIEŻOŚCI,2.02,25,MARGINALNE
278,334.00,HEYAH,99.93,5,MARGINALNE
279,335.00,LYCAMOBILE,107.34,4,MARGINALNE
280,337.00,TELEGROSIK,248.78,3,MARGINALNE
281,338.00,VIRGIN,16.26,1,MARGINALNE
295,353.00,Wcielone z Transportera,0.00,69,ZERO - brak sprzedaży
296,354.00,xinne,8.23,4,MARGINALNE

In [1796]:
## Ilość transakcji na SKU
prog = 500
def klasyfikuj_tx(val):
    if val <100:    return 'D - brak'
    if (val >=100 and val < prog):    return 'C - sporadyczny'
    if (val>=prog and val<=1000):     return 'B - regularny'
    return 'A - popularny'

sku = df.groupby(['SKU', 'Nazwa_towar']).agg(
    transakcje=('DokId', 'nunique'),
    wartosc=('Wartosc', 'sum'),
    ilosc=('ilosc_netto', 'sum')
).reset_index()

sku['klasa_tx'] = sku['transakcje'].apply(klasyfikuj_tx)

print(sku['klasa_tx'].value_counts())

klasa_tx
D - brak           16185
C - sporadyczny     3770
B - regularny       1198
A - popularny        712
Name: count, dtype: int64

In [1797]:
# Klasyfikacja per kategoria AsId
prog = 500

def klasyfikuj_tx(val):
    if val < 100:                    return 'D - brak'
    if val >= 100 and val < prog:    return 'C - sporadyczny'
    if val >= prog:                  return 'B - regularny'
    return 'A - popularny'

asid = df.groupby(['AsId', 'Nazwa_asort']).agg(
    transakcje=('DokId', 'nunique'),
    wartosc=('Wartosc', 'sum'),
    ilosc_sku=('SKU', 'nunique')
).reset_index()

asid['klasa_tx'] = asid['transakcje'].apply(klasyfikuj_tx)

print(asid['klasa_tx'].value_counts())
print()
print(asid.sort_values('transakcje', ascending=True).to_string())

klasa_tx
B - regularny      191
D - brak            68
C - sporadyczny     39
Name: count, dtype: int64

      AsId                               Nazwa_asort  transakcje    wartosc  ilosc_sku         klasa_tx
281 338.00                                    VIRGIN           2      16.26          1         D - brak
278 334.00                                     HEYAH           4      99.93          5         D - brak
168 180.00                         INNE /przemysłowe           5       0.00          3         D - brak
45   48.00                    DOŁADOWANIA I STARTERY           5       0.00          2         D - brak
44   47.00                             x DOŁADOWANIA           5       0.00         14         D - brak
53   56.00                            BIO /kosmetyki           5       0.00         22         D - brak
159 170.00                    AGD I RTV /przemysłowe           5       0.00          2         D - brak
229 248.00                SMAKOSZ /dodatki spożywcze           5       0.00          1         D - brak
164 176.00  ARTYKUŁY SEZONOWE I DEKORACJE /przemysło           5       0.00          5         D - brak
265 318.00                                     LUBIE           5       0.00         11         D - brak
166 178.00    DESKI, SUSZARKI, POKROWCE /przemysłowe           5       0.00          1         D - brak
49   52.00                PREZERWATYWY /farmaceutyki           5      -1.04          8         D - brak
170 183.00              MATERIAŁY PALNE /przemysłowe           5       0.00          1         D - brak
127 136.00            CHLEBY I POCHODNE /dietetyczne           5       0.00          1         D - brak
173 186.00            SERWETKI I OBRUSY /przemysłowe           5       0.00         17         D - brak
253 300.00                HERBATY ZIOŁA KAWY /zdrowa           5       0.00          5         D - brak
48   51.00            PARAFARMACEUTYKI /farmaceutyki           5      20.93          2         D - brak
248 291.00                                   TOREBKI           5       0.00          5         D - brak
247 290.00           09 KARTY TEL. doładowania KIOSK           5       0.00         12         D - brak
236 259.00                    Grot Surówki i sałatki           5       0.00          2         D - brak
245 288.00                   13 PUNKT DO WERYFIKACJI           5       0.00          1         D - brak
238 275.00                       08 BATERIE W KIOSKU           5      -4.45         14         D - brak
230 249.00                               EKO /nabiał           5       0.00          1         D - brak
244 285.00                     01 PAPIEROSY W KIOSKU           5       0.00          1         D - brak
123 131.00                            INNE POZOSTAŁE           5       0.00          2         D - brak
241 279.00                          ŻARÓWKI W KIOSKU           5       0.00         12         D - brak
279 335.00                                LYCAMOBILE           6     107.34          4         D - brak
217 234.00           MARGARYNY DO SMAŻENIA /tłuszcze           6       0.00          1         D - brak
226 244.00        Domyślny DO WERYFIKACJI + PRZECENY           6     138.49          2         D - brak
51   54.00                               x KOSMETYKI           7     405.87         30         D - brak
240 278.00                      12 PRZEMYSŁOWE KIOSK           7       1.77         21         D - brak
249 293.00                          02 TYTOŃ W KIOSK           7       0.00          1         D - brak
296 354.00                                     xinne           7       8.23          4         D - brak
267 320.00                                       BIO           8       0.00          9         D - brak
61   65.00          ZESTAWY I KOSMETYCZKI /kosmetyki           8     416.83          2         D - brak
101 107.00                           OWOCE I WARZYWA           8       0.00          2         D - brak
134 145.00                             SOKI I NAPOJE           8       0.00          2         D - brak
130 139.00         SŁODYCZE DIETETYCZNE /dietetyczne           8       0.00          2         D - brak
231 252.00                                     Lubię           8       0.00          6         D - brak
197 210.00                         OWOCE MORZA /ryby           8       0.00          4         D - brak
128 137.00             INNE DIETETYCZNE /dietetyczne           8       0.00          7         D - brak
126 135.00        BATONY I WAFELKI DIET /dietetyczne           8       0.00         11         D - brak
235 258.00                              GROT PIEROGI           8       0.00         10         D - brak
31   33.00                         DODATKI SPOŻYWCZE           8       0.00          1         D - brak
243 284.00                             11 LEKI KIOSK          10     109.33         13         D - brak
280 337.00                                TELEGROSIK          12     248.78          3         D - brak
274 328.00                       STRAŻNICY ŚWIEŻOŚCI          15       2.02         25         D - brak
246 289.00              KARNET I KOPERTY I POCZTÓWKI          16      75.42         28         D - brak
232 255.00         Doładowania PayUp - bez terminala          18    2100.00          3         D - brak
120 126.00              PIZZE, ZAPIEKANKI I CEBULAKI          19     124.00          4         D - brak
268 321.00                  WEGETARIAŃSKIE/WEGAŃSKIE          19      93.36          6         D - brak
132 143.00                        MLEKA MODYFIKOWANE          24     965.04          3         D - brak
50   53.00          ŚRODKI OPATRUNKOWE /farmaceutyki          28     216.50         15         D - brak
60   64.00                      DZIECIĘCE /kosmetyki          31     530.10         10         D - brak
175 188.00           ŚRODKI OWADOBÓJCZE /przemysłowe          31     264.49         16         D - brak
242 283.00                        06 BILETY W KIOSKU          35     118.70          5         D - brak
239 277.00                      05 ZAPALNICZKI KIOSK          42     304.23         17         D - brak
180 193.00                    PRZETWORY DANIA GOTOWE          42     875.15          7         D - brak
160 171.00         AKCESORIA DO KĄPIELI /przemysłowe          45     250.03         12         D - brak
63   67.00                                GARMAŻERKA          47     591.00          4         D - brak
252 298.00                       ŚWIECE /przemysłowe          54     392.74         39         D - brak
177 190.00                      ZABAWKI /przemysłowe          55      79.18         11         D - brak
47   50.00                        LEKI /farmaceutyki          55     864.72          2         D - brak
295 353.00                   Wcielone z Transportera          61       0.00         69         D - brak
186 199.00                KOMPOTY /przetwory owocowe          71    1024.71          2         D - brak
291 348.00                          MIĘSO PACZKOWANE          74    1007.28          9         D - brak
251 296.00                   FAJERWERKI /przemysłowe          75     541.61         28         D - brak
64   68.00                       MIĘSO DROBIOWE WAGA          79     983.50          2         D - brak
228 247.00                   OPAKOWANIA /przemysłowe         109     491.44          5  C - sporadyczny
14   16.00            ODPLAM WYBIEL KROCHMAL /chemia         117    1117.17          9  C - sporadyczny
158 169.00                             x PRZEMYSŁOWE         121    1160.03         58  C - sporadyczny
56   60.00                      PAZNOKCIE /kosmetyki         126    1375.43         19  C - sporadyczny
163 175.00             ARTYKUŁY GRILOWE /przemysłowe         127    1761.61         27  C - sporadyczny
7     9.00                 x PAPIERNICZO HIGIENICZNE         132    1181.36          8  C - sporadyczny
277 332.00                                  T-MOBILE         143    3867.13          5  C - sporadyczny
282 339.00                                      INNE         147    9757.99         10  C - sporadyczny
22   24.00                          DODATKI DESEROWE         148    1185.19          8  C - sporadyczny
255 304.00                        SPOŻWCZE POZOSTAŁE         154    1141.48          1  C - sporadyczny
108 114.00                    SURÓWKI I SAŁATKI WAGA         161    1597.77          3  C - sporadyczny
156 167.00                       PRECELKI /przekąski         189    1975.48          4  C - sporadyczny
52   55.00          DEZODORANTY I PERFUMY /kosmetyki         190    3089.46         73  C - sporadyczny
13   15.00                                    CHEMIA         204    2511.66         23  C - sporadyczny
264 317.00                               PIELĘGNACJA         228    5676.25         10  C - sporadyczny
74   80.00                         RYBY MROŻONE WAGA         229    6706.59          4  C - sporadyczny
161 172.00          AKCES DO SPRZĄTANIA /przemysłowe         232    1397.35         53  C - sporadyczny
250 295.00                             SŁODYCZE KURI         232    1012.73         34  C - sporadyczny
133 144.00                                   POSIŁKI         240    4422.22         33  C - sporadyczny
275 330.00                                      PLUS         240    6847.26          7  C - sporadyczny
59   63.00                          WŁOSY /kosmetyki         248    4461.21         65  C - sporadyczny
271 324.00                                    ĆWIKŁY         249    2572.75          2  C - sporadyczny
16   18.00                              SZYB /chemia         252    3820.67         13  C - sporadyczny
97  103.00                             NAPOJE GORĄCE         255    3044.84          3  C - sporadyczny
169 181.00   KWIATY, DONICZKI I DODATKI /przemysłowe         268    5505.09         11  C - sporadyczny
90   96.00                                    NAPOJE         276    3932.12          3  C - sporadyczny
15   17.00             ODŚWIEŻACZE POWIETRZA /chemia         287    5572.29         43  C - sporadyczny
54   57.00           GOLENIA I DEPILACJIA /kosmetyki         322    2901.63         28  C - sporadyczny
293 351.00                            GRZYBY MROŻONE         333   13757.82          5  C - sporadyczny
222 239.00                           OLIWY /tłuszcze         387   15986.67         25  C - sporadyczny
46   49.00                            x FARMACEUTYKI         391    8309.92         35  C - sporadyczny
188 201.00              MARMOLADY /przetwory owocowe         393    4672.29          7  C - sporadyczny
165 177.00                      BATERIE /przemysłowe         394    5509.98         27  C - sporadyczny
103 109.00                                    GRZYBY         411   11293.05          5  C - sporadyczny
259 309.00                               1 CYDR 4,5%         420    7095.18         25  C - sporadyczny
276 331.00                                      PLAY         428   11918.26          6  C - sporadyczny
176 189.00                    TEKSTYLIA /przemysłowe         443    8259.02         40  C - sporadyczny
201 215.00                   RYBY WĘDZONE WAGA /ryby         469    7324.74          3  C - sporadyczny
105 111.00                          NASIONA I ZIARNA         494    5737.75          9  C - sporadyczny
129 138.00              PRODUKTY SOJOWE /dietetyczne         532    5345.40          5    B - regularny
131 142.00                                    KASZKI         541   11289.90         19    B - regularny
272 325.00                      SZYBKIE DANIA GOTOWE         550   13321.98         21    B - regularny
171 184.00         NACZYNIA JEDNORAZOWE /przemysłowe         596    5150.75         49    B - regularny
162 174.00           AKCESORIA KUCHENNE /przemysłowe         623    5736.54         42    B - regularny
119 125.00                          PIECZYWO TOSTOWE         625    6345.86          8    B - regularny
212 227.00                       ROGALIKI I BABECZKI         627    4119.55         17    B - regularny
57   61.00                  CIAŁO I TWARZ /kosmetyki         640    9870.81         61    B - regularny
167 179.00                FOLIE I WORKI /przemysłowe         643    6404.64         40    B - regularny
204 218.00                             CIASTA GOTOWE         656   12115.67         91    B - regularny
58   62.00                     JAMA USTNA /kosmetyki         683    8101.50         58    B - regularny
0     2.00               3 ALKOHOLE INNE POWYŻEJ 18%         743   35444.06         35    B - regularny
283 340.00                                    ORANGE         752   17697.17          6    B - regularny
254 301.00                                      RYBY         760   25154.23          3    B - regularny
36   38.00                                  ZAPRAWKI         784    5015.49          6    B - regularny
19   21.00                          PŁUKANIE /chemia         819   20474.36         67    B - regularny
139 150.00     BATONY ZBOŻOWE, MUSLI /zdrowa żywność         841    5984.53          8    B - regularny
17   19.00                       CZYSZCZENIE /chemia         854   14568.04         74    B - regularny
125 133.00                             GAZETY /prasa         877    3217.85        525    B - regularny
104 110.00                            GRZYBY SUSZONE         949   25825.74          8    B - regularny
10   12.00  PŁATKI, WACIKI I PATYCZKI /papierniczo h         989    7720.24         28    B - regularny
190 203.00                POWIDŁA /przetwory owocowe        1015   16803.27          4    B - regularny
179 192.00              ZNICZE I WKŁADY /przemysłowe        1019   27363.14        113    B - regularny
66   71.00                              WĘDLINY WAGA        1032   18499.35         15    B - regularny
196 209.00                    RYBY I PRZETWORY RYBNE        1037   14242.07         29    B - regularny
200 214.00                        RYBY WĘDZONE /ryby        1042   27356.42         19    B - regularny
135 146.00                                 ZWIERZETA        1111   11355.85         34    B - regularny
110 116.00                           WARZYWA KISZONE        1128   12243.79         16    B - regularny
144 155.00                  OTRĘBY /zbożowe i sypkie        1134    9136.91          6    B - regularny
138 149.00                          ZBOŻOWE I SYPKIE        1153   16379.90          9    B - regularny
25   27.00  DEKORACJE I MASY, AROMATY /dodatki deser        1157   14674.27         20    B - regularny
67   72.00                                  MROŻONKI        1183   21971.13         11    B - regularny
73   79.00                        RYBY I OWOCE MORZA        1219   34479.59         20    B - regularny
289 346.00                             MASY DO CIAST        1239   19609.15         19    B - regularny
258 308.00                          2 LIKIERY DO 18%        1329   63084.88         45    B - regularny
285 342.00                                   AROMATY        1341    7610.93         12    B - regularny
20   22.00                            PRANIE /chemia        1379   31336.26         84    B - regularny
174 187.00                       SZKOŁA /przemysłowe        1403   17758.60         91    B - regularny
215 232.00          MARGARYNY DO PIECZENIA /tłuszcze        1480   11028.59          5    B - regularny
218 235.00           MARGARYNY UNIVERSALNE /tłuszcze        1555   14696.38          6    B - regularny
256 306.00                          1 DRINKI DO 4,5%        1658   30763.13         18    B - regularny
149 160.00                                 PRZEKĄSKI        1661   28629.53          5    B - regularny
172 185.00                  PREZENTÓWKA /przemysłowe        1756   17510.65         66    B - regularny
55   58.00                    MYCIA CIAŁA /kosmetyki        1830   23423.94        170    B - regularny
116 122.00         GROSZEK PTYSIOWY, GRZANKI DO ZUPY        1849   28979.56          7    B - regularny
71   77.00                             OWOCE MROŻONE        1860   52117.07         13    B - regularny
290 347.00                                      MUSY        1862   21681.16         31    B - regularny
137 148.00                            KARMY DLA PSÓW        1936   29034.79         69    B - regularny
9    11.00         PAPIER TOALETOWY /papierniczo hig        1953   43474.99         52    B - regularny
12   14.00        RĘCZNIKI KUCHENNE /papierniczo hig        1966   26362.51         30    B - regularny
286 343.00                                 DEKORACJE        2047   28258.72         46    B - regularny
206 220.00                              CIASTKA WAGA        2129   22491.26         26    B - regularny
21   23.00                                WC /chemia        2181   42968.00         82    B - regularny
225 243.00                                     TYTOŃ        2246  136384.89         28    B - regularny
28   30.00     KREMY DO SMAROWANIA /dodatki deserowe        2353   54306.56         24    B - regularny
3     5.00         2 WINA MUSUJĄCE I SZAMPANY do 18%        2387   85147.03         57    B - regularny
112 118.00                               BUŁKA TARTA        2575   28647.04         11    B - regularny
262 314.00                            ORYGINALNY SOK        2615   83841.16         53    B - regularny
122 128.00                           TORTILLE I PITY        2651   50435.24         10    B - regularny
29   31.00                   MIODY /dodatki deserowe        2673   53540.66         15    B - regularny
8    10.00   CHUSTECZKI HIGIENICZNE /papierniczo hig        2679   15747.74         44    B - regularny
34   36.00         DANIA KUB 5MIN /dodatki spożywcze        2744   48064.83         56    B - regularny
202 216.00                                x SŁODYCZE        2753   25326.34         85    B - regularny
121 127.00                                   SUCHARY        2853   42531.85         24    B - regularny
178 191.00        ZAPALNICZKI I ZAPAŁKI /przemysłowe        2944    9509.32         30    B - regularny
11   13.00  PODPASKI, TAMPONY I WKŁADKI /papierniczo        2961   40813.04         56    B - regularny
154 165.00                       POP CORN /przekąski        3173   36358.81         15    B - regularny
187 200.00              KONFITURY /przetwory owocowe        3387   73873.20         17    B - regularny
263 315.00                                ŚWIĄTECZNE        3439   66315.02        134    B - regularny
62   66.00               MIĘSO, WĘDLINY I GARMAŻERKA        3445   79471.26         35    B - regularny
33   35.00                 CHRZAN /dodatki spożywcze        3460   35841.82         17    B - regularny
77   83.00                                    NABIAŁ        3585   17616.29          7    B - regularny
195 208.00            ZUPY GOTOWE /przetwory owocowe        3617   54287.48         14    B - regularny
24   26.00        CIASTA W PROSZKU /dodatki deserowe        3678   69824.07         46    B - regularny
18   20.00                          NACZYNIA /chemia        3693   53764.68         56    B - regularny
287 344.00                                   DODATKI        3713   48554.22         22    B - regularny
257 307.00                           PIWA 0% 5% VATU        3737   52924.90         61    B - regularny
4     6.00           3 WHISKY RUM BRANDY RUM BOURBON        3751  257782.17        124    B - regularny
224 242.00                       AKCESORIA tytoniowe        3766   40097.11        146    B - regularny
191 204.00         PRZECIERY INNE /przetwory owocowe        3805   43245.54         13    B - regularny
99  105.00                KAKAO I ZABIELACZE DO KAWY        3821   56679.56         31    B - regularny
152 163.00                       ORZESZKI /przekąski        3834   66580.42         35    B - regularny
260 312.00                               WIELKANOCNE        3918   66882.85        128    B - regularny

In [1798]:
for klasa in ['D - brak', 'C - sporadyczny', 'B - regularny']:
    print(f"\n=== {klasa} ===")
    print(asid[asid['klasa_tx'] == klasa][['AsId', 'Nazwa_asort', 'transakcje', 'wartosc']].to_string())

=== D - brak ===
      AsId                               Nazwa_asort  transakcje  wartosc
31   33.00                         DODATKI SPOŻYWCZE           8     0.00
44   47.00                             x DOŁADOWANIA           5     0.00
45   48.00                    DOŁADOWANIA I STARTERY           5     0.00
47   50.00                        LEKI /farmaceutyki          55   864.72
48   51.00            PARAFARMACEUTYKI /farmaceutyki           5    20.93
49   52.00                PREZERWATYWY /farmaceutyki           5    -1.04
50   53.00          ŚRODKI OPATRUNKOWE /farmaceutyki          28   216.50
51   54.00                               x KOSMETYKI           7   405.87
53   56.00                            BIO /kosmetyki           5     0.00
60   64.00                      DZIECIĘCE /kosmetyki          31   530.10
61   65.00          ZESTAWY I KOSMETYCZKI /kosmetyki           8   416.83
63   67.00                                GARMAŻERKA          47   591.00
64   68.00                       MIĘSO DROBIOWE WAGA          79   983.50
101 107.00                           OWOCE I WARZYWA           8     0.00
120 126.00              PIZZE, ZAPIEKANKI I CEBULAKI          19   124.00
123 131.00                            INNE POZOSTAŁE           5     0.00
126 135.00        BATONY I WAFELKI DIET /dietetyczne           8     0.00
127 136.00            CHLEBY I POCHODNE /dietetyczne           5     0.00
128 137.00             INNE DIETETYCZNE /dietetyczne           8     0.00
130 139.00         SŁODYCZE DIETETYCZNE /dietetyczne           8     0.00
132 143.00                        MLEKA MODYFIKOWANE          24   965.04
134 145.00                             SOKI I NAPOJE           8     0.00
159 170.00                    AGD I RTV /przemysłowe           5     0.00
160 171.00         AKCESORIA DO KĄPIELI /przemysłowe          45   250.03
164 176.00  ARTYKUŁY SEZONOWE I DEKORACJE /przemysło           5     0.00
166 178.00    DESKI, SUSZARKI, POKROWCE /przemysłowe           5     0.00
168 180.00                         INNE /przemysłowe           5     0.00
170 183.00              MATERIAŁY PALNE /przemysłowe           5     0.00
173 186.00            SERWETKI I OBRUSY /przemysłowe           5     0.00
175 188.00           ŚRODKI OWADOBÓJCZE /przemysłowe          31   264.49
177 190.00                      ZABAWKI /przemysłowe          55    79.18
180 193.00                    PRZETWORY DANIA GOTOWE          42   875.15
186 199.00                KOMPOTY /przetwory owocowe          71  1024.71
197 210.00                         OWOCE MORZA /ryby           8     0.00
217 234.00           MARGARYNY DO SMAŻENIA /tłuszcze           6     0.00
226 244.00        Domyślny DO WERYFIKACJI + PRZECENY           6   138.49
229 248.00                SMAKOSZ /dodatki spożywcze           5     0.00
230 249.00                               EKO /nabiał           5     0.00
231 252.00                                     Lubię           8     0.00
232 255.00         Doładowania PayUp - bez terminala          18  2100.00
235 258.00                              GROT PIEROGI           8     0.00
236 259.00                    Grot Surówki i sałatki           5     0.00
238 275.00                       08 BATERIE W KIOSKU           5    -4.45
239 277.00                      05 ZAPALNICZKI KIOSK          42   304.23
240 278.00                      12 PRZEMYSŁOWE KIOSK           7     1.77
241 279.00                          ŻARÓWKI W KIOSKU           5     0.00
242 283.00                        06 BILETY W KIOSKU          35   118.70
243 284.00                             11 LEKI KIOSK          10   109.33
244 285.00                     01 PAPIEROSY W KIOSKU           5     0.00
245 288.00                   13 PUNKT DO WERYFIKACJI           5     0.00
246 289.00              KARNET I KOPERTY I POCZTÓWKI          16    75.42
247 290.00           09 KARTY TEL. doładowania KIOSK           5     0.00
248 291.00                                   TOREBKI           5     0.00
249 293.00                          02 TYTOŃ W KIOSK           7     0.00
251 296.00                   FAJERWERKI /przemysłowe          75   541.61
252 298.00                       ŚWIECE /przemysłowe          54   392.74
253 300.00                HERBATY ZIOŁA KAWY /zdrowa           5     0.00
265 318.00                                     LUBIE           5     0.00
267 320.00                                       BIO           8     0.00
268 321.00                  WEGETARIAŃSKIE/WEGAŃSKIE          19    93.36
274 328.00                       STRAŻNICY ŚWIEŻOŚCI          15     2.02
278 334.00                                     HEYAH           4    99.93
279 335.00                                LYCAMOBILE           6   107.34
280 337.00                                TELEGROSIK          12   248.78
281 338.00                                    VIRGIN           2    16.26
291 348.00                          MIĘSO PACZKOWANE          74  1007.28
295 353.00                   Wcielone z Transportera          61     0.00
296 354.00                                     xinne           7     8.23

=== C - sporadyczny ===
      AsId                              Nazwa_asort  transakcje  wartosc
7     9.00                x PAPIERNICZO HIGIENICZNE         132  1181.36
13   15.00                                   CHEMIA         204  2511.66
14   16.00           ODPLAM WYBIEL KROCHMAL /chemia         117  1117.17
15   17.00            ODŚWIEŻACZE POWIETRZA /chemia         287  5572.29
16   18.00                             SZYB /chemia         252  3820.67
22   24.00                         DODATKI DESEROWE         148  1185.19
46   49.00                           x FARMACEUTYKI         391  8309.92
52   55.00         DEZODORANTY I PERFUMY /kosmetyki         190  3089.46
54   57.00          GOLENIA I DEPILACJIA /kosmetyki         322  2901.63
56   60.00                     PAZNOKCIE /kosmetyki         126  1375.43
59   63.00                         WŁOSY /kosmetyki         248  4461.21
74   80.00                        RYBY MROŻONE WAGA         229  6706.59
90   96.00                                   NAPOJE         276  3932.12
97  103.00                            NAPOJE GORĄCE         255  3044.84
103 109.00                                   GRZYBY         411 11293.05
105 111.00                         NASIONA I ZIARNA         494  5737.75
108 114.00                   SURÓWKI I SAŁATKI WAGA         161  1597.77
133 144.00                                  POSIŁKI         240  4422.22
156 167.00                      PRECELKI /przekąski         189  1975.48
158 169.00                            x PRZEMYSŁOWE         121  1160.03
161 172.00         AKCES DO SPRZĄTANIA /przemysłowe         232  1397.35
163 175.00            ARTYKUŁY GRILOWE /przemysłowe         127  1761.61
165 177.00                     BATERIE /przemysłowe         394  5509.98
169 181.00  KWIATY, DONICZKI I DODATKI /przemysłowe         268  5505.09
176 189.00                   TEKSTYLIA /przemysłowe         443  8259.02
188 201.00             MARMOLADY /przetwory owocowe         393  4672.29
201 215.00                  RYBY WĘDZONE WAGA /ryby         469  7324.74
222 239.00                          OLIWY /tłuszcze         387 15986.67
228 247.00                  OPAKOWANIA /przemysłowe         109   491.44
250 295.00                            SŁODYCZE KURI         232  1012.73
255 304.00                       SPOŻWCZE POZOSTAŁE         154  1141.48
259 309.00                              1 CYDR 4,5%         420  7095.18
264 317.00                              PIELĘGNACJA         228  5676.25
271 324.00                                   ĆWIKŁY         249  2572.75
275 330.00                                     PLUS         240  6847.26
276 331.00                                     PLAY         428 11918.26
277 332.00                                 T-MOBILE         143  3867.13
282 339.00                                     INNE         147  9757.99
293 351.00                           GRZYBY MROŻONE         333 13757.82

=== B - regularny ===
      AsId                               Nazwa_asort  transakcje    wartosc
0     2.00               3 ALKOHOLE INNE POWYŻEJ 18%         743   35444.06
1     3.00                            1 PIWO BUTELKA       25605  476134.94
2     4.00                             1 PIWO PUSZKA       30284  536412.21
3     5.00         2 WINA MUSUJĄCE I SZAMPANY do 18%        2387   85147.03
4     6.00           3 WHISKY RUM BRANDY RUM BOURBON        3751  257782.17
5     7.00               2 WINA, MIÓD NALEWKA DO 18%        8321  361515.67
6     8.00             3 WÓDKI I NAP.ALK POWYŻEJ 18%       52788 2209227.85
8    10.00   CHUSTECZKI HIGIENICZNE /papierniczo hig        2679   15747.74
9    11.00         PAPIER TOALETOWY /papierniczo hig        1953   43474.99
10   12.00  PŁATKI, WACIKI I PATYCZKI /papierniczo h         989    7720.24
11   13.00  PODPASKI, TAMPONY I WKŁADKI /papierniczo        2961   40813.04
12   14.00        RĘCZNIKI KUCHENNE /papierniczo hig        1966   26362.51
17   19.00                       CZYSZCZENIE /chemia         854   14568.04
18   20.00                          NACZYNIA /chemia        3693   53764.68
19   21.00                          PŁUKANIE /chemia         819   20474.36
20   22.00                            PRANIE /chemia        1379   31336.26
21   23.00                                WC /chemia        2181   42968.00
23   25.00                 BUDYNIE /dodatki deserowe       11124   95445.12
24   26.00        CIASTA W PROSZKU /dodatki deserowe        3678   69824.07
25   27.00  DEKORACJE I MASY, AROMATY /dodatki deser        1157   14674.27
26   28.00               GALARETKI /dodatki deserowe       10326  136873.63
27   29.00        KISIELE, OWSIANKI SŁODKIE CHWILE /       12665  149108.01
28   30.00     KREMY DO SMAROWANIA /dodatki deserowe        2353   54306.56
29   31.00                   MIODY /dodatki deserowe        2673   53540.66
30   32.00   PRODUKTY DO PIECZENIA /dodatki deserowe       11409   85523.41
32   34.00                BULIONY /dodatki spożywcze       13488  189948.40
33   35.00                 CHRZAN /dodatki spożywcze        3460   35841.82
34   36.00         DANIA KUB 5MIN /dodatki spożywcze        2744   48064.83
35   37.00         FIXY W PROSZKU /dodatki spożywcze       13238  218181.38
36   38.00                                  ZAPRAWKI         784    5015.49
37   39.00               KETCHUPY /dodatki spożywcze        9522  163336.78
38   40.00               MAJONEZY /dodatki spożywcze       15582  307648.09
39   41.00              MUSZTARDY /dodatki spożywcze       12066  101468.29
40   42.00                   OCTY /dodatki spożywcze        6240   60447.25
41   43.00                                 PRZYPRAWY       16927  168562.07
42   44.00         SOSY W PROSZKU /dodatki spożywcze       10359  112978.20
43   46.00                   ZUPY /dodatki spożywcze       25137  384708.11
55   58.00                    MYCIA CIAŁA /kosmetyki        1830   23423.94
57   61.00                  CIAŁO I TWARZ /kosmetyki         640    9870.81
58   62.00                     JAMA USTNA /kosmetyki         683    8101.50
62   66.00               MIĘSO, WĘDLINY I GARMAŻERKA        3445   79471.26
65   70.00                        WĘDLINY PACZKOWANE       32074  771127.10
66   71.00                              WĘDLINY WAGA        1032   18499.35
67   72.00                                  MROŻONKI        1183   21971.13
68   73.00                      DANIA GOTOWE MROŻONE        5514  167023.43
69   74.00                                    FRYTKI        5388  134356.32
70   75.00                                      LODY       40439 1090743.81
71   77.00                             OWOCE MROŻONE        1860   52117.07
72   78.00                        PIZZA I ZAPIEKANKI        4271  126074.00
73   79.00                        RYBY I OWOCE MORZA        1219   34479.59
75   81.00                            WARZYWA I MIXY       10622  228004.66
76   82.00                              ZUPY MROŻONE        7361  163299.01
77   83.00                                    NABIAŁ        3585   17616.29
78   84.00                            DESERY /nabiał       28496  472755.73
79   85.00             JAJA I PASTY JAJECZNE /nabiał       22013  544920.78
80   86.00                           JOGURTY /nabiał       56726  854081.72
81   87.00                 KEFIRY I MAŚLANKI /nabiał       15561  198222.46
82   88.00                             MLEKO /nabiał       60747  854343.44
83   89.00                 MLEKO ZAGĘSZCZONE /nabiał       11331  161402.13
84   90.00                              SERY /nabiał       35293  716984.10
85   91.00                      SERY TOPIONE /nabiał        9778  147011.65
86   92.00                         SERY WAGA /nabiał       50896  871444.34
87   93.00                 ŚMIETANKI DO KAWY /nabiał        5412   57801.20
88   94.00                          ŚMIETANY /nabiał       39801  478611.43
89   95.00                           TWAROGI /nabiał       59251  976175.06
91   97.00                    ENERGETYKI I IZOTONIKI       47135  549769.69
92   98.00                           NAPOJE GAZOWANE       67404 1016082.77
93   99.00                        NAPOJE NIEGAZOWANE       52187  685036.66
94  100.00                            SOKI I NEKTARY       40345  580384.08
95  101.00                 SYROPY I SOKI ZAGĘSZCZONE       13786  276554.33
96  102.00                                      WODY       79895  679860.27
98  104.00                                   HERBATY       29356  552361.62
99  105.00                KAKAO I ZABIELACZE DO KAWY        3821   56679.56
100 106.00                                      KAWY       34172  909876.27
102 108.00                        BAKALIE PACZKOWANE        4658   86607.96
104 110.00                            GRZYBY SUSZONE         949   25825.74
106 112.00                                     OWOCE       77156  990894.80
107 113.00                         SURÓWKI I SAŁATKI        7956  109275.07
109 115.00                                   WARZYWA       73607  920111.72
110 116.00                           WARZYWA KISZONE        1128   12243.79
111 117.00                                  PIECZYWO       45250  398507.76
112 118.00                               BUŁKA TARTA        2575   28647.04
113 119.00                                     BUŁKI       70137  535363.62
114 120.00                                    CHLEBY       32565  315883.87
115 121.00                       DROŻDŻÓWKI I PĄCZKI        7408   62850.03
116 122.00         GROSZEK PTYSIOWY, GRZANKI DO ZUPY        1849   28979.56
117 123.00                         PIECZYWO CHRUPKIE        6608  104185.22
118 124.00         PIECZYWO O PRZEDŁUŻONEJ TRWAŁOŚCI       16965  247813.75
119 125.00                          PIECZYWO TOSTOWE         625    6345.86
121 127.00                                   SUCHARY        2853   42531.85
122 128.00                           TORTILLE I PITY        2651   50435.24
124 132.00                                     PRASA       26809  369232.31
125 133.00                             GAZETY /prasa         877    3217.85
129 138.00              PRODUKTY SOJOWE /dietetyczne         532    5345.40
131 142.00                                    KASZKI         541   11289.90
135 146.00                                 ZWIERZETA        1111   11355.85
136 147.00                           KARMY DLA KOTÓW        3958   72603.33
137 148.00                            KARMY DLA PSÓW        1936   29034.79
138 149.00                          ZBOŻOWE I SYPKIE        1153   16379.90
139 150.00     BATONY ZBOŻOWE, MUSLI /zdrowa żywność         841    5984.53
140 151.00                  CUKIER /zbożowe i sypkie       16299  220553.02
141 152.00                   KASZE /zbożowe i sypkie       10419  132489.14
142 153.00                MAKARONY /zbożowe i sypkie       38855  594853.81
143 154.00                    MĄKI /zbożowe i sypkie       15703  193832.96
144 155.00                  OTRĘBY /zbożowe i sypkie        1134    9136.91
145 156.00      PŁATKI ŚNIADANIOWE /zbożowe i sypkie       10398  225528.37
146 157.00          PŁATKI ZBOŻOWE /zbożowe i sypkie        5284   67461.56
147 158.00                    RYŻE /zbożowe i sypkie       11303  149589.10
148 159.00                     SÓL /zbożowe i sypkie        9576   67878.25
149 160.00                                 PRZEKĄSKI        1661   28629.53
150 161.00                         CHIPSY /przekąski       24541  565874.14
151 162.00                       KRAKERSY /przekąski        8237  100030.84
152 163.00                       ORZESZKI /przekąski        3834   66580.42
153 164.00                       PALUSZKI /przekąski       19732  265656.89
154 165.00                       POP CORN /przekąski        3173   36358.81
155 166.00             PRAŻYNKI I CHRUPKI /przekąski       16675  224020.16
157 168.00                ZIARNA I PESTKI /przekąski        4650   51044.93
162 174.00           AKCESORIA KUCHENNE /przemysłowe         623    5736.54
167 179.00                FOLIE I WORKI /przemysłowe         643    6404.64
171 184.00         NACZYNIA JEDNORAZOWE /przemysłowe         596    5150.75
172 185.00                  PREZENTÓWKA /przemysłowe        1756   17510.65
174 187.00                       SZKOŁA /przemysłowe        1403   17758.60
178 191.00        ZAPALNICZKI I ZAPAŁKI /przemysłowe        2944    9509.32
179 192.00              ZNICZE I WKŁADY /przemysłowe        1019   27363.14
181 194.00            DANIA GOTOWE /przetwory mięsne        5145  144847.46
182 195.00         KONSERWY MIĘSNE /przetwory mięsne        6721  184534.77
183 196.00                PASZTETY /przetwory mięsne       13655  147773.41
184 197.00                PRZETWORY OWOCOWO-WARZYWNE        3919   53810.77
185 198.00                  DŻEMY /przetwory owocowe       11945  171089.73
187 200.00              KONFITURY /przetwory owocowe        3387   73873.20
189 202.00                OWOCOWE /przetwory owocowe       14925  269621.76
190 203.00                POWIDŁA /przetwory owocowe        1015   16803.27
191 204.00         PRZECIERY INNE /przetwory owocowe        3805   43245.54
192 205.00   PRZETWORY POMIDOROWE /przetwory owocowe       17849  260523.62
193 206.00            SOSY GOTOWE /przetwory owocowe       10447  212251.30
194 207.00               WARZYWNE /przetwory owocowe       25029  427157.74
195 208.00            ZUPY GOTOWE /przetwory owocowe        3617   54287.48
196 209.00                    RYBY I PRZETWORY RYBNE        1037   14242.07
198 211.00                     PRZETWORY RYBNE /ryby       13014  252147.87
199 213.00                     RYBY W PUSZKACH /ryby        5490   84616.22
200 214.00                        RYBY WĘDZONE /ryby        1042   27356.42
202 216.00                                x SŁODYCZE        2753   25326.34
203 217.00                          BATONY I WAFELKI       58297  774488.56
204 218.00                             CIASTA GOTOWE         656   12115.67
205 219.00                                   CIASTKA       53241  893000.79
206 220.00                              CIASTKA WAGA        2129   22491.26
207 221.00                                  CUKIERKI       41075  433219.41
208 222.00                             CUKIERKI WAGA       11882  118787.14
209 223.00                                 CZEKOLADY       28810  558430.38
210 224.00                             GUMY DO ŻUCIA        7487   66518.84
211 226.00                     BOMBONIERKI I PRALINY       10419  376503.72
212 227.00                       ROGALIKI I BABECZKI         627    4119.55
213 228.00                        SŁODYCZE POZOSTAŁE        6114   62244.71
214 230.00                  WAFLE I PODKŁADY TORTOWE       11432  137572.74
215 232.00          MARGARYNY DO PIECZENIA /tłuszcze        1480   11028.59